체크리스트 질문 조회 기능을 리팩토링한다.
woowacourse-teams/2024-bang-ggood pull request #150
Opened 2024-07-27 14:20 UTC by shin-jisong

## ❗ Issue
- #144 

## ✨ 구현한 기능
- 체크리스트 질문 조회 기능 구조 변경

## 📢 논의하고 싶은 내용

## 🎸 기타
- questionlist를 삭제하고 Question에 enum 자료형을 도입하였습니다
- Question에  questionId를 추가하고 Category에서 제외하였습니다
- enum이라는 자료형이 가지고 있는 가독성과 열거형이라는 특성에 맞게 이름 부여를 고민해 보았습니다
- 제 구현 부분 외적인 다른 코드는 주석 처리해 두었습니다 이후 병합 과정에서 리팩토링에 맞게 합치면 될 듯합니다!

2024-07-27 15:27 UTC, tkdgur0906 requested changes
리팩토링하느라 고생많으셨습니다!
Question을 enum으로 변경한 것에 대해서만 서로 통일하면 문제 없을 것 같네요!

2024-07-27 15:27 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
> +public enum Question {
QuestionList 없애고 Question을 enum으로 두었을 때의 느끼신 장점이 궁금합니다!

2024-07-28 08:39 UTC, JINU-CHANG reviewed
Question을 Enum으로 변경한 이유가 궁금하네요!
이외 다른 코멘트는 없습니다~

2024-07-28 08:39 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +                    String answer = existQuestions.getOrDefault(questionId, null);
👍👍👍

2024-07-29 07:53 UTC, merged

2024-07-29 07:53 UTC, tkdgur0906 approved these changes