Refactor/144 read checklist question
woowacourse-teams/2024-bang-ggood pull request #151
Opened 2024-07-27 14:25 UTC by shin-jisong

## ❗ Issue
- #144

## ✨ 구현한 기능
- 체크리스트 질문 조회 기능을 리팩토링하며 구조 변경

## 📢 논의하고 싶은 내용

## 🎸 기타
- questionlist를 삭제하고 Question에 enum 자료형을 도입하였습니다
- Question에  questionId를 추가하고 Category에서 제외하였습니다
- enum이라는 자료형이 가지고 있는 가독성과 열거형이라는 특성에 맞게 이름 부여를 고민해 보았습니다
- 제 구현 부분 외적인 다른 코드는 주석 처리해 두었습니다 이후 병합 과정에서 리팩토링에 맞게 합치면 될 듯합니다!

2024-07-27 15:38 UTC, tkdgur0906 requested changes
리팩토링 깔끔하니 좋네요~
회의 때 의견 맞춰보고 approve 하겠습니다!

2024-07-27 15:38 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +            List<QuestionResponse> questionsByCategory = Question.findQuestionsByCategory(category)
굉장히 깔끔해졌네요👍

2024-07-27 15:38 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
> +public enum Question {
https://github.com/woowacourse-teams/2024-bang-ggood/pull/150#discussion_r1693975865

이 코멘트와 동일한 부분이라 여기서 답변부탁드립니다!

2024-07-28 11:10 UTC, tsulocalize requested changes

2024-07-28 11:10 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
> +    ROOM_CONDITION_11(11, Category.ROOM_CONDITION, "벽지 상태가 양호한가요?", null),
prefix로 구분하게 해놓았으니 ROOM_CONDITION_1부터 시작하는 건 어떨까요?

2024-07-29 08:00 UTC, merged