토스트 컴포넌트를 전역으로 수정하고, zIndex를 테마 상수화 시킨다.
woowacourse-teams/2024-bang-ggood pull request #155
Opened 2024-07-28 09:35 UTC by ooherin

## ❗ Issue
#62 

## ✨ 구현한 기능

### 제대로 된 토스트로 리팩토링 

- 기존에 토스트의 경우 state를 모두 내부에서 적어야 한다는 단점이 있었습니다. 또한 
  해당 컴포넌트에 직접 toast 가 렌더링 되어, 해당 페이지를 벗어나면 토스트가 보이지  않는 버그가 있었습니다.

- 이를 해결하기 위해, toastProvider 를 만들어 토스트를 전역으로 사용 할 수 있도록 하였습니다. 

### z-index 상수화 

- 또한 토스트의 경우 모달 보다 위에 떠야 하기 때문에 z-index 를 주어야 했습니다. 
- z-index를 5개의 레벨로 나누어 theme 안에서 선언했습니다. 이제 z-index 의 경우 theme 을 사용하시면 될 것 같습니다! 
- 현재 z-index 를 사용하고 있는 곳은 3곳이며 다음과 같이 레벨을 정의했습니다. 
- (1) floatingButton: LEVEL1
- (2) modal: LEVEL2
- (3) toast: LEVEL3

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-07-28 10:19 UTC, skiende74 approved these changes
수고하셨습니다 👍

코멘트 하나 적어뒀는데 꼭 반영하라는건아니고
거기에 대해 답변만 달아주세요 :)

2024-07-28 10:19 UTC, skiende74 commented on frontend/src/styles/theme.ts
> +};
이건 무조건 반영해달라는 건 아니고, 그냥 제안인데
토스트가 LEVEL-3인지, LEVEL-2인지 외우는 것도 일이니까
'FLOATING_BUTTON' : 10
'MODAL' : 20,
'TOAST' : 30,

이런식으로 관리하면 어떨까요?
누가 위에오는지 확인하고싶어질때도 이 파일만 확인하면 되어서 더 편할거같습니다 !

2024-07-28 10:45 UTC, skiende74 commented on frontend/src/components/common/Toast/Toast.stories.tsx
> +    );
Fragment(<>)는 빼주셔도 될거같습니다

2024-07-28 11:18 UTC, skiende74 commented on frontend/src/components/common/Toast/Toast.stories.tsx
> +  args: { duration: 3 },
duration을 100으로 바꿔도, 토스트는 3초만 발생하네요.
코드내부에서는 정작 TOAST_DURATION = 3을 사용하고있어서 그런거같아요

duration이 적용되도록 코드를 작성해서 `refactor/62-toast-duration`이라는 새로운 브랜치에 push 해두었으니
참고해서 고쳐주세요 !

2024-07-28 11:22 UTC, ooherin commented on frontend/src/styles/theme.ts
> +};
오 좋은데요? 사실이것도 고려하긴 했는데
매번 사용할때마다 재선언이 귀찮은 단점이 있더라구요 다 장단이 있는것같아요😅
하지만 이번프로젝트에서는 zindex가 몇번 안쓰일것같으니 제이드 의견대로 해보죠!!👍👍

2024-07-28 11:27 UTC, skiende74 requested changes
> duration을 100으로 바꿔도, 토스트는 3초만 발생하네요.
코드내부에서는 정작 TOAST_DURATION = 3을 사용하고있어서 그런거같아요.
duration이 적용되도록 변경한 코드를 refactor/62-toast-duration이라는
새로운 브랜치에 push 해두었으니 고쳐서 사용하셔도 됩니다 :)

새로운 이슈를 발견하여서 반영부탁드립니다 👍

2024-07-28 11:30 UTC, skiende74 commented on frontend/src/styles/theme.ts
> +};
저는 level로만 쓰다가 이번에 갑자기 떠올라서 제안해보았었는데
장단점이 있군요 ㅎㅎ

2024-07-28 23:50 UTC, ooherin commented
제이드 리팩토링 된 코드 잘 봤습니다! 개인적으로 context 안에 로직을 훅으로 뺸 것은 정말 좋다고 생각합니다. 하지만 토스트 컴포넌트 내에 있는 useEffect 로직을 굳이 외부로 뺄 필요는 없을 것 같습니다. 이유는 다음과 같습니다.

1. setTimeout으로 UI 가 변경되는 것은 로직이 아닌 toast의 UI 적 역할임 (toast의 생명 주기는 컴포넌트에서 관리하는 것이 적절함)
2. 단일 책임 원칙을 지킬 수 있음. showToast의 경우 '토스트 메세지를 변경해준다' 역할을, toast는 그 로직을 duration 동안 띄워주는 역할을 함.
3. 컴포넌트가 언마운트 될 때 자동으로 타이머가 클리어되는 등 메모리 관리가 더 용이.

제이드가 hook 으로 수정한 위에 2개의 커밋만 사용하도록 하겠습니다. 덕분에 다른 방식도 생각해 보게 되네요. 감사합니다:)👍👍

2024-07-29 01:10 UTC, ooherin commented
+ 제이드의 의도를 이제야 파악했네요! toast의 duration을 상태로 외부러 꺼내서 설정할 수 있게 하신 것 같습니다! 
물론 토스트의 의도로 좋지만, 서비스의 통일성을 위해서 default_duration 만 사용하는 것도 괜찮다는 생각이 드네요.
약간 오버 엔지니어링일 수 있겠다라는 생각이요! 매번 토스트를 쓸 때마다 duration을 생각하는 것도 일일 것 같아서요. 제이드의 의견은 어떠세요?

2024-07-29 01:41 UTC, skiende74 commented
> * 제이드의 의도를 이제야 파악했네요! toast의 duration을 상태로 외부러 꺼내서 설정할 수 있게 하신 것 같습니다!
>   물론 토스트의 의도로 좋지만, 서비스의 통일성을 위해서 default_duration 만 사용하는 것도 괜찮다는 생각이 드네요.
>   약간 오버 엔지니어링일 수 있겠다라는 생각이 들어요. 매번 토스트를 쓸 때마다 duration을 생각하는 것도 일일 것 같아서요. 제이드의 의견은 어떠세요?
> 
> 현재는 duration 을 toast에서 default_duration 을 해당 파일에서 선언해서 사용해 주었습니다!

그게 의도였다면 적용하지않으셔도 됩니다 :)

approve할게요

의미를 예시로 더 잘전달하려고 코드를 썼던건데
오히려 그걸보느라 시간을 썼을수도있겠네요. 미안해요

고생하셨습니다.

2024-07-29 01:41 UTC, skiende74 approved these changes
Approve

2024-07-29 05:05 UTC, healim01 approved these changes
코드 확인했습니다. 제이드 말처럼 Floating_button 으로 zindex 상수 이름을 픽스하는게 좋을거 같아요~!

2024-07-29 05:26 UTC, merged