체크리스트 방 정보 작성 API에 기능을 추가 구현한다
woowacourse-teams/2024-bang-ggood pull request #189
Opened 2024-07-31 08:24 UTC by shin-jisong

## ❗ Issue
- #182 

## ✨ 구현한 기능
- Checklist 도메인에 필드 추가
- Room 도메인에 필드 추가
- 체크리스트 방 정보 작성 로직 수정
- 각종 예외 사항 처리

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-07-31 13:39 UTC, tsulocalize requested changes

2024-07-31 13:39 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
> +import static com.bang_ggood.checklist.domain.ChecklistScore.calculateCategoryScore;
import 순서가 기존에 정한 순서랑 다른 것 같아요!

2024-07-31 15:36 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        if (room.getFloorLevel() != FloorLevel.GROUND && room.getFloor() != null) {
도메인 Room이 검증하게 해보는건 어떨까요??

2024-07-31 15:38 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +                        question.memo()))
Grade처럼 findById대신 from를 사용해보는건 어떨까요??

2024-08-01 01:23 UTC, tkdgur0906 approved these changes
간단히 의견만 여쭤봅니다!
고생하셨습니다!

2024-08-01 01:23 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/FloorLevel.java
> +    public static FloorLevel from(String name) {
함수 네이밍을 from, fromName중 어떤게 낫다고 생각하시나요?

2024-08-01 01:51 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
> +import static com.bang_ggood.checklist.domain.ChecklistScore.calculateCategoryScore;
현재 BE 코드 컨벤션에 작성되어 있는 것들은 다 적용하였는데 어떤 부분일까요?

2024-08-01 01:52 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
>  public enum ExceptionCode {
👍👍👍

2024-08-01 01:52 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        if (room.getFloorLevel() != FloorLevel.GROUND && room.getFloor() != null) {
Service의 영역이라 생각했는데 충분히 room에서 할 수 있는 로직이네요! 반영하였습니다 👍

2024-08-01 02:17 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +                        question.memo()))
기존에 구현되어 있는 함수를 사용하였는데 fromId라는 명명이 더 적절하겠네요! 변경해 주었습니다

2024-08-01 02:17 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/FloorLevel.java
> +    public static FloorLevel from(String name) {
내부 필드가 하나일 경우 from을 사용하고 여러 개일 경우 세부 필드를 명명으로 표시하는 게 좋다 생각했습니다! 카피는 어떻게 생각하시나요??

2024-08-01 02:19 UTC, JINU-CHANG approved these changes

2024-08-01 02:27 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
> +import static com.bang_ggood.checklist.domain.ChecklistScore.calculateCategoryScore;
수정하였습니다~

2024-08-01 02:35 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/FloorLevel.java
> +    public static FloorLevel from(String name) {
저도 동의합니다! 하나 있을떄는 From으로 가시죠

2024-08-01 02:35 UTC, tsulocalize approved these changes

2024-08-01 02:35 UTC, merged