[BE] 커스텀 체크리스트 수정 기능을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #191
Opened 2024-07-31 09:08 UTC by tsulocalize

## ❗ Issue

- #183 

## ✨ 구현한 기능
- schema 수정 (custom-checklist 테이블 추가)
- CustomChecklist 도메인 추가
- CustomChecklist 수정 API 추가

## 📢 논의하고 싶은 내용
[id - question - user]를 담은 도메인 이름으로 CustomChecklist 보다 CustomQuestion이 적절한 것 같아 적용해보았는데, 의견 부탁드립니다. (제 3의견: CustomChecklistQuestion)

## 🎸 기타
이후 해야할 일
- 체크리스트 생성 시, CustomChecklist로부터 생성하도록 로직 수정
- 유저 생성 시, default 질문을 담은 CustomChecklist를 생성하는 기능 추가

2024-07-31 16:02 UTC, JINU-CHANG reviewed
간단한 코멘트 남겨두었습니다 확인해주세요 😊

2024-07-31 16:02 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +    @DisplayName("커스텀 체크리스트 업데이트 실패 : 질문 개수가 유효하지 않을 때")
앞의 코멘트와 마찬가지로, `질문의 개수가 유효하지 않을 때`보다는 `질문이 존재하지 않을 때`이 더 맞는 표현같아보여요!

2024-07-31 16:02 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/resources/data.sql
> +INSERT INTO custom_question(user_id, question, created_at, modified_at)
👍👍👍

2024-08-01 01:27 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        Map<Category, List<Question>> categoryQuestions = customQuestions.stream()
제제의 생각을 조금 더 자세히 말해줄 수 있을까요? 감이 잘 안잡히네요...

2024-08-01 01:32 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +    }
👍 반영했습니다!

2024-08-01 01:32 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +    @DisplayName("커스텀 체크리스트 업데이트 실패 : 질문 개수가 유효하지 않을 때")
👍 반영했습니다!

2024-08-01 01:32 UTC, shin-jisong reviewed
> [id - question - user]를 담은 도메인 이름으로 CustomChecklist 보다 CustomQuestion이 적절한 것 같아 적용해보았는데, 의견 부탁드립니다. (제 3의견: CustomChecklistQuestion)

회의 당시 custumQuestion은 질문 자체를 커스텀한다는 느낌이 강하여 나중에 질문 작성 커스텀이 생길 때 두 부분의 혼동이 생길 것을 우려하여 CustomChecklist로 결정했던 걸로 기억해요 하지만 우주의 의견에도 동의해서 제 3의 의견이 가장 적절해 보이네요~!

2024-08-01 01:32 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        Map<Category, List<Question>> categoryQuestions = customQuestions.stream()
지금 방안도 충분히 고심하셨을 것 같지만 Question 내에 Category 정보가 있으니 내부에 이미 있는 메서드를 이용하거나 새로 생성하여 로직을 짜는 것도 좋을 듯하네요!

2024-08-01 01:32 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
> +    CUSTOM_CHECKLIST_INVALID_COUNT(HttpStatus.BAD_REQUEST, "커스텀 질문 개수가 유효하지 않습니다.");
도메인 명을 따라가기로 했는데 도메인 명과 일치하지 않네요! 도메인명이 변경될 수도 있을 것 같으니 추후 수정해 주시면 될 듯해요 👍

2024-08-01 01:32 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +        CustomChecklistUpdateRequest request = new CustomChecklistUpdateRequest(List.of(1, 3, 5, 7, 8, 11, 15, 30));
길이가 길지 않아 괜찮지만 Fixture로 뺄 수도 있는 부분이겠네요! 
(모든 테스트 객체 생성에 동일한 리뷰이니 전체적으로 참고해 주세요)

2024-08-01 01:36 UTC, tkdgur0906 requested changes
간단한 코멘트만 남겼습니다~
확인해주세요!

2024-08-01 01:36 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/CustomQuestion.java
> +    @Enumerated(value = EnumType.STRING)
기존 코드들이 enumberated에서 value가 default라 생략하고 있어서 여기도 맞춰주시면 좋을 것 같아요!

2024-08-01 01:37 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/CustomQuestion.java
> +    @Enumerated(value = EnumType.STRING)
👍 반영했습니다!

2024-08-01 01:44 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
> +    CUSTOM_CHECKLIST_INVALID_COUNT(HttpStatus.BAD_REQUEST, "커스텀 질문 개수가 유효하지 않습니다.");
👍 반영했습니다!

2024-08-01 07:17 UTC, JINU-CHANG approved these changes

2024-08-01 07:30 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        Map<Category, List<Question>> categoryQuestions = customQuestions.stream()
더 나은 방법을 고민해봤는데 쉽게 결론이 나지 않았습니다;;
우선 이대로 가겠습니다!

2024-08-01 07:33 UTC, tkdgur0906 approved these changes
고생.

2024-08-01 07:33 UTC, shin-jisong approved these changes

2024-08-01 07:36 UTC, merged