[BE] 카카오 서버로부터 사용자 정보를 가져온다.
woowacourse-teams/2024-bang-ggood pull request #198
Opened 2024-08-01 07:11 UTC by JINU-CHANG

## ❗ Issue

- #181 

## ✨ 구현한 기능

- 프론트로부터 전달받은 **인가코드**를 이용해 카카오 서버에 **토큰**을 요청하는 기능을 구현했습니다.
- RestClient를 사용해 API를 요청했고, RestClientExceptionHandler로 에러 핸들링을 구현했습니다.
- exception 패키지와 handler 패키지를 분리하고 exception 내부에 dto 패키지를 생성했습니다.
- 토큰을 가지고 카카오 서버에 **사용자 정보**를 요청하는 기능을 구현했습니다.

## 📢 논의하고 싶은 내용

## 🎸 기타

- 추후 진행 예정 사항
  - 회원가입/로그인 진행 
  - 프론트에서 인가코드에 대한 기능 구현이 완료되면 코드 정상작동하는지 확인 필요. 현재는 에러 메시지를 통해 카카오 서버에 API 요청이 간다는 것까지만 확인했습니다.

2024-08-01 08:16 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/controller/UserController.java
> +}
카카오 로그인인 걸 명시적으로 나타내면 어떨까요?

2024-08-01 08:16 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/config/RestClientConfig.java
> +                .build();
timeout 설정 하는 건 어떻게 생각하시나요?

2024-08-01 08:33 UTC, shin-jisong reviewed
작성되어 있는 코멘트 말고 추가적인 코멘트를 남길 건 없어 보여요!
나중에 최종 구현이 되고 한번 더 확인해 보겠습니다~

2024-08-01 09:15 UTC, tkdgur0906 requested changes
몇가지 리뷰 남겼습니다!
확인부탁드려요!!!!!

2024-08-02 06:09 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/service/OauthClient.java
> +            @Value("${kakao.token_post_uri}") String tokenRequestUri,
`@ConfigurationProperties`은 `@Value`로 값들을 하나하나 지정해주는게 불편해서 사용하는 것이라고 이해했는데요,
`@ConfigurationProperties`을 사용했을 때 새로운 클래스를 만들어 값을 관리하는 것보다 `@Value`를 사용하는데 더 쉽다고 느꼈어요. 크게 불편한 부분도 없었던 것 같고요! 해당 어노테이션을 사용했을 때의 확실한 장점이 있다면 적용해보겠습니다~

2024-08-02 06:11 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/config/RestClientConfig.java
> +public class RestClientConfig {
너무 좋은데요?! 👍

2024-08-02 06:13 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/config/RestClientConfig.java
> +    RestClient restClient(RestClientExceptionHandler handler) {
좋은 의견인것 같아요 👍
저도 인터페이스를 고민해봤으나 지금 당장은 필요하지 않다고 판단해서 작업하지 않았습니다! 
추후에 소셜로그인이 추가된다면 그때는 인터페이스를 적용해보면 좋을 것 같아요~

2024-08-02 06:25 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/controller/UserController.java
> +}
나중에 다른 소셜 로그인이 추가되면 그때 넣어도 좋을 것 같아요~

2024-08-02 06:33 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/config/RestClientConfig.java
> +                .build();
타임아웃은 조금만 더 공부하고 넣고 싶어서 다음 PR에 적용해보도록 하겠습니다!

2024-08-02 06:41 UTC, shin-jisong approved these changes

2024-08-02 06:43 UTC, tkdgur0906 approved these changes
구현하느라 고생많으셨어요!

2024-08-02 07:02 UTC, tsulocalize approved these changes

2024-08-02 07:02 UTC, merged