체크리스트 수정 API를 구현한다.
woowacourse-teams/2024-bang-ggood pull request #213
Opened 2024-08-03 06:57 UTC by shin-jisong

## ❗ Issue
- #205 

## ✨ 구현한 기능
-  방 정보 수정 기능
- 체크리스트 옵션 삭제 후 재등록
- 체크리스트 질문의 경우, 답변과 메모만 수정

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-08-03 07:23 UTC, tkdgur0906 reviewed
테스트 꼼꼼히 작성해주셔서 너무 좋네요!
간단한 코멘트만 남겼습니다~

2024-08-03 07:23 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
> +    @DisplayName("체크리스트 수정 성공")
값이 수정 되었는지도 같이 테스트해보면 좋을 것 같긴한데,
서비스 로직으로 충분하다고 생각하시면 유지하셔도 좋습니다!

2024-08-03 08:21 UTC, tsulocalize requested changes

2024-08-03 08:21 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +    }
List 순서가 다르면 test가 깨지는데, 이는 의도된 사항일까요?

2024-08-03 08:21 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistQuestion.java
> +    }
현재 Question이 Enum이므로,
```java
this.question != checklistQuestion.question
```
으로 구현해도 좋을 것 같네요!

2024-08-04 09:30 UTC, JINU-CHANG requested changes
수고하셨습니다 😊

2024-08-04 09:30 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +    }
해당 로직이 잘 이해되지 않는 것 같아요 🥲

2024-08-04 09:30 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
> +                .statusCode(400);
이런식으로 에러 메시지도 검증해볼 수 있을 것 같아요!

```
        RestAssured.given().log().all()
                .contentType(ContentType.JSON)
                .header(new Header(HttpHeaders.COOKIE, expectedCookie))
                .when().post("/categories/priority")
                .then().log().all()
                .statusCode(401)
                .body("message", containsString(ExceptionCode.AUTHENTICATION_COOKIE_INVALID.getMessage()));
    }
```

2024-08-05 06:36 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
> +    @DisplayName("체크리스트 수정 성공")
해당 단계에 로직이 존재하는 것만 테스트로 작성하였습니다!

2024-08-05 06:42 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
> +    public ResponseEntity<Void> createChecklist(@Valid @RequestBody ChecklistRequest checklistRequest) {
저희가 수정의 정책을 put으로 고정하면서 작성과 수정이 항상 같은 DTO 형태와 검증 기준을 유지하고 있는데 공용으로 사용하기 위해 적절한 네이밍으로 변경하였습니다

2024-08-05 06:44 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
> +    public ResponseEntity<Void> createChecklist(@Valid @RequestBody ChecklistRequest checklistRequest) {
> 저희가 수정의 정책을 put으로 고정하면서 작성과 수정이 항상 같은 DTO 형태와 검증 기준을 유지하고 있는데 공용으로 사용하기 위해 적절한 네이밍으로 변경하였습니다

위에 답변에 덧붙여서 같은 검증 로직을 유지하고 있는데 현재로서는 분리하는 것이 유지하는 데 더 큰 노력을 소요한다 생각하여 합쳤습니다 혹시 update에서 patch 등으로 정책이 바뀐다면 그때 분리하는 게 어떨까요?

2024-08-05 06:47 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +    }
저희가 정책적으로 json의 순서를 그대로 저장하고 그대로 제공하는 것으로 정하여서 해당 부분도 그렇게 구현하였습니다~

2024-08-05 06:51 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        checklist.change(updateChecklist);
해당 부분을 고려해 보았으나 repository적인 네이밍이라 생각하여 대안으로 change로 명명해 보았습니다!
entity 안에 들어가는 변경 함수의 명명이 update인 게 너무 repository와 밀접하지 않은가 하는 우려였습니다
하지만 update를 위한 함수이니 어쩔 수 없다의 생각도 있어요~ 제제는 어떻게 생각하시나요?

2024-08-05 07:48 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistOptionRepository.java
> +    void deleteAllByChecklistId(long checklistId);
반영하였습니다~

2024-08-05 07:51 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistQuestion.java
> +    }
반영하였습니다~

2024-08-05 07:55 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +                checklistInfo.contractTerm(), checklistInfo.realEstate());
시도해 봤는데 데이터 일치 문제로 오류가 생겨 불가한 방법이었습니다 🥲

2024-08-05 07:56 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        validateOptions(optionIds);
밑에서도 사용하는데 두 번 이상 사용하는 부분은 따로 변수로 빼 주었습니다~

2024-08-05 07:58 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        checklistOptionRepository.saveAll(checklistOptions);
옵션의 경우에는 항목 자체가 변화하는 부분이라 전체 삭제 후 전체 저장 방식을 택하였습니다
반면에 질문의 경우 질문 id 자체는 유지가 되어야 하고 답변과 메모만 변화하는 방식이라 수정 방식을 택하였습니다!

2024-08-05 08:10 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        List<ChecklistQuestion> updateQuestions = checklistRequest.questions().stream()
고민해 보았는데 해당 객체를 만들기 위해 업데이트 과정에서 완성된 checklist 객체를 request 객체에 삽입해 줘야 하는 흐름이 부적절하게 느껴져서 service에서 만들도록 작성해 보았습니다!

2024-08-05 08:11 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +    }
기존 질문리스트와 업데이트 될 질문 리스트들을 하나씩 비교하여 업데이트 해 주는 방식이에요 어떤 부분을 개선하면 좋다 생각하시나요?

2024-08-05 08:13 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
> +                .statusCode(400);
해당 부분은 DTO에서 검증하는 부분이라 DTO의 에러 메시지가 변경되면 테스트 코드도 변경될 것 같아 메시지 검증에 대한 부분을 생략하였어요!
하지만 포함하는 것이 더 정확할 것 같아 반영하였습니다 👍

2024-08-05 08:43 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
> +    public ResponseEntity<Void> createChecklist(@Valid @RequestBody ChecklistRequest checklistRequest) {
넵~ 알겠습니다!

2024-08-05 08:58 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +    }
시소의 의견을 반영해서 이부분은 추후 리팩토링 작업으로 미루는게 좋아보이네요!

2024-08-05 08:58 UTC, JINU-CHANG approved these changes

2024-08-05 09:00 UTC, tsulocalize approved these changes

2024-08-05 09:00 UTC, tkdgur0906 approved these changes

2024-08-05 09:01 UTC, merged