[BE] 방 비교 결과 조회 API에 기능을 추가 구현한다.
woowacourse-teams/2024-bang-ggood pull request #215
Opened 2024-08-03 09:52 UTC by tkdgur0906

## ❗ Issue

- #197 

## ✨ 구현한 기능
- 체크리스트 랭킹 계산 기능
- 질문 미 선택 시 null 처리
- 논리적 삭제 정책 반영

## 📢 논의하고 싶은 내용
미 선택 질문에 대한 답변을 전체 점수 계산에 반영할 지에 대한 여부

## 🎸 기타

2024-08-03 14:12 UTC, tsulocalize requested changes

2024-08-03 14:12 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        }
index를 기준으로 값을 부여하는 건 좋아보이지 않네요. 더 나은 방법이 없을까요?

2024-08-04 07:47 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistWithScoreReadResponse.java
> +    }
없어도 될듯합니다👍

2024-08-04 09:56 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
> +    long countAllByIdIn(@Param("user") User user, @Param("ids") List<Long> ids);
count 쿼리 대신 유저의 리스트를 조회해와서 크기를 validate하는 방식으로 변경했습니다!

2024-08-04 10:54 UTC, JINU-CHANG reviewed
수고많으셨습니다 👏👏👏 
궁금한부분 몇개 코멘트 남겨두었어요~

2024-08-04 10:54 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +        System.out.println(response);
오잉 이거 맞나요??

2024-08-04 10:54 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        }
`.sorted(Comparator.comparing(ChecklistWithScoreReadResponse::getScore).reversed())`

이미 정렬이 되어 있으니 이 순서로 for문 돌면서 rank 부여하면 될 것 같은데 ChecklistRank.calculateRanksByDescendingScores(scores)의 역할을 잘 모르겠어요 🥲

2024-08-05 05:53 UTC, shin-jisong requested changes
간단하게 리뷰 남겼습니다! 수고하셨어요~

2024-08-05 05:53 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
> +        if(grade == null) {
공백이 제대로 들어가지 않은 것 같아요
정책상 수정될 코드 같기는 하네요~

2024-08-05 05:53 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistWithScoreReadResponse.java
> +public class ChecklistWithScoreReadResponse {
record에서 class로 바꾼 이유가 있으신가요?

2024-08-05 05:53 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
> +    @Query("SELECT c FROM Checklist c "
쿼리를 따로 작성한 코드에 대해서는 테스트를 작성해 보아도 좋을 것 같습니다~

2024-08-05 05:53 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
>          int checklistScore = ChecklistScore.calculateTotalScore(checklist.getQuestions());
ChecklistScore를 호출하기 위해 체크리스트의 질문들을 꺼내서 넣는 게 어색하게 느껴져요!
checklist 내부에서 checklistScore를 갖고 있고 결과값을 넘기는 함수를 구현하는 게 어떨까요?
고려만 해 주세요 ㅎㅎ

2024-08-05 05:53 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
> +    SCORE_NOT_DESCENDING_SORTED(HttpStatus.BAD_REQUEST, "정렬되지 않은 점수입니다."),
에러코드 컨벤션에 맞게 수정해 보는 건 어떨까요?

2024-08-05 05:53 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistRankTest.java
> +class ChecklistRankTest {
꼼꼼하게 테스트해 주셨네요 👍

2024-08-05 06:49 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        }
전체적인 구현방식을 바꿔 인덱스 대신 객체에 직접 값을 할당하는 방법으루 수정하였습니다!

2024-08-05 06:55 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +        System.out.println(response);
크흠 수정했습니다!

2024-08-05 06:55 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        }
전체적인 구현방식을 바꿔 인덱스 대신 객체에 직접 값을 할당하는 방법으루 수정하였습니다!

2024-08-05 06:57 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
> +        if(grade == null) {
정책에 맞게 수정해놨습니다!

2024-08-05 06:58 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistWithScoreReadResponse.java
> +public class ChecklistWithScoreReadResponse {
객체 생성시 rank를 할당할 수가 없는데 Record를 사용할 경우 setter 사용이 불가했습니다.
rank 계산 후 값을 할당해주기 위해 class로 변경하였습니다!

2024-08-05 07:05 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
> +    SCORE_NOT_DESCENDING_SORTED(HttpStatus.BAD_REQUEST, "정렬되지 않은 점수입니다."),
Score 분류를 따로 만들어서 분류했습니다!

2024-08-05 07:10 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
>          int checklistScore = ChecklistScore.calculateTotalScore(checklist.getQuestions());
해당 부분을 고민해봤는데 저희가 oneToMany를 제거하면 해당로직도 작동하지 않게 되어서,
아예 checklistQuestionRepository에서 질문들을 조회하는 방식으로 구현해야할 것 같습니다!

다만 [ 방 체크리스트 조회](https://github.com/woowacourse-teams/2024-bang-ggood/pull/219) 해당 pr이 열려있어서 여기에서 반영하도록 하겠습니다!

2024-08-05 08:58 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
> +    @Query("SELECT c FROM Checklist c "
작성 완료!

2024-08-05 10:03 UTC, tsulocalize approved these changes

2024-08-05 10:06 UTC, JINU-CHANG approved these changes

2024-08-05 10:07 UTC, merged