인증 로직을 추가한다.
woowacourse-teams/2024-bang-ggood pull request #218
Opened 2024-08-04 07:37 UTC by JINU-CHANG

## ❗ Issue

- #217 

## ✨ 구현한 기능

- `@AuthenticationPrincipal` 어노테이션 생성
  - 다음과 같이 인증이 필요한 API의 파라미터에 추가할 수 있습니다.
  ```
  @PostMapping("/categories/priority")
  public ResponseEntity<Void> createCategoriesPriority(@AuthenticationPrincipal AuthUser authUser, @RequestBody 
  CategoryPriorityCreateRequest request) {
          categoryService.createCategoriesPriority(authUser, request);
          return ResponseEntity.noContent().build();
  }
  ```
- AuthenticationPrincipalArgumentResolver 클래스 생성
- JwtTokenProvider 클래스 내 resolveToken() 메서드 예외처리 기능 추가 및 테스트 코드 작성

## 📢 논의하고 싶은 내용

- `@AuthenticationPrincipal`, `AuthenticationPrincipalArgumentResolver` 어떤 패키지가 적절할지 의견 궁금합니다!
- 인증이 필요한 API 리스트업하려면 회의가 필요하지 않을까 한데,, 월요일날 이야기해봐요!

## 🎸 기타

2024-08-04 09:13 UTC, tkdgur0906 requested changes
구현하느라 고생 많으셨습니다! 역쉬 제제👍
슬쩍 코멘트 한번 확인해주세용~

2024-08-04 09:13 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
> +    Optional<User> findByEmail(String email);
여기도 논리적 삭제 적용 해야할 것 같아요!

2024-08-05 06:04 UTC, shin-jisong requested changes
나머지는 지난 리뷰와 동일한 리뷰라 겹치지 않게 작성했습니다! 수고하셨어요~
+) 본문의 내용은 구두로 답변드렸습니다!

2024-08-05 06:04 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoResponse.java
> +
저도 기존에 저희가 생성하는 response와 다른 명칭을 가지면 좋겠다는 말에 동의해요~

2024-08-05 07:10 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/AuthenticationPrincipalArgumentResolver.java
> +    public boolean supportsParameter(MethodParameter parameter) {
반영했습니다~

2024-08-05 07:27 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoResponse.java
> +
> OauthInfoResponse가 클라이언트로 반환되는게 아니라 서비스에서만 사용되는 것 같은데 Response 단어를 빼보는 것도 괜찮을 것 같긴해요!

`OauthInfoResponse`가 DTO역할을 하는데, Response단어를 빼면 서비스 코드에서 도메인과 헷갈리게 될 것 같아서 Response를 붙였습니다!

> 다만 client로 보내는 response와 다른 이름을 가지면 좋을 것 같긴 하네요 (such as ***ApiResponse)

Oauth가 소셜 로그인임을 뜻하고 있어서 지금으로도 괜찮지 않을까요??

2024-08-05 07:59 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoResponse.java
> +
-> Oauth를 한 번 더 인식해야하는 것이 힘들다, Api로 외부 Api임을 알려줄 수 있다는 의견을 반영해서 `OauthInfoApiResponse`로 바꿨습니다~!

2024-08-05 07:59 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
> +    Optional<User> findByEmail(String email);
적용했습니다!

2024-08-06 00:55 UTC, tsulocalize requested changes

2024-08-06 00:55 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/BaseEntity.java
> +    }
저는 BaseEntity가 delete()를 갖는 것보다 repository.delete()가 더 나은 것 같아요!
전자는 entity.delete() 이후 repository.save()를 해야해서 2번 일하는 느낌? 이 들어요

2024-08-06 00:55 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
> +    @DisplayName("유저 조회 성공 : 이메일로 유저 조회할 때")
DisplayName과 테스트 내용이 일치하지 않는 것 같아요!

2024-08-06 01:25 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
> +    public static final String TOKEN_COOKIE_NAME = "token";
다른 곳에서 사용되어서 public으로 두겠습니다!

2024-08-06 03:17 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/BaseEntity.java
> +    }
@tkdgur0906 @shin-jisong 다른 분들은 어떻게 생각하시나요?

2024-08-06 03:20 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
> +    @DisplayName("유저 조회 성공 : 이메일로 유저 조회할 때")
반영했습니다~

2024-08-06 05:00 UTC, tsulocalize approved these changes

2024-08-06 05:20 UTC, shin-jisong approved these changes

2024-08-06 05:20 UTC, merged