[BE] 체크리스트 조회 API에 기능을 추가 구현한다.
woowacourse-teams/2024-bang-ggood pull request #219
Opened 2024-08-04 07:43 UTC by tkdgur0906

## ❗ Issue

- #184  

## ✨ 구현한 기능
- 체크리스트 생성 시간을 반환
-  논리적 삭제 도입

## 📢 논의하고 싶은 내용
선택하지 않은 Grade를 null 대신에 NONE이라는 값으로 저장하는 것이 필요할 것 같음
-> 답변하지 않은 질문도 조회해야 하기 때문

## 🎸 기타

2024-08-05 06:08 UTC, shin-jisong requested changes
간단한 내용만 작성했습니다! 특별히 언급드릴 부분은 보이지 않네요 수고하셨어요~

2024-08-05 06:08 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
> +        if (grade == null) {
오늘 데일리에서 얘기된 부분이기는 하지만 이 부분 수정해도 되겠네요!

2024-08-05 06:46 UTC, JINU-CHANG approved these changes
따로 코멘트할 건 없어보이네용! approve하겠습니다 👍

2024-08-05 09:50 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
> +        if (grade == null) {
수정했습니다!

2024-08-06 03:09 UTC, shin-jisong approved these changes

2024-08-06 03:09 UTC, merged