[BE] 체크리스트 좋아요를 추가한다.
woowacourse-teams/2024-bang-ggood pull request #303
Opened 2024-08-10 15:44 UTC by tkdgur0906

## ❗ Issue

- #298 

## ✨ 구현한 기능

- 체크리스트 좋아요 추가

## 📢 논의하고 싶은 내용

- 체크리스트에 대한 User 검증을 추가하면서 다른 api들과 동일한 검증 로직을 사용하게 될 것 같은데, 추후 클래스 분리가 필요할 것 같습니다.

## 🎸 기타

2024-08-11 03:50 UTC, JINU-CHANG requested changes
빠르게 구현해주셨네요! 수고하셨습니다 😺

2024-08-11 03:50 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistLikeRepository.java
> +    boolean existsByChecklist(Checklist checklist);
`@Param` 어노테이션 붙여주세요~

2024-08-11 03:50 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        }
`getUser().equals(user)`
-> 유저의 체크리스트인지 물어보는 메서드가 계속 쓰일 것 같아서 하나의 메서드로 만들어두면 좋을 것 같아요~

2024-08-11 03:50 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
> +    LIKE_ALREADY_EXISTS(HttpStatus.CONFLICT, "체크리스트가 이미 좋아요 상태입니다"),
CONFLICT이라는 것도 있군요 👍

2024-08-11 04:05 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistLikeRepository.java
> +    boolean existsByChecklist(Checklist checklist);
'@Query' 사용할때만 Param 필요한걸루 알고있어 안붙였습니다!

2024-08-11 07:17 UTC, tsulocalize reviewed
추가할 코멘트 없습니다!
dev-be merge 되면 approve 할게요~

2024-08-11 08:30 UTC, shin-jisong approved these changes
수고하셨습니다 간단한 리뷰만 남기고 approve 할게요~

2024-08-11 08:30 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
> +    @DisplayName("체크리스트 좋아요 추가 실패 : 이미 좋아요가 추가가 된 체크리스트인 경우")
이 부분은 service 테스트 영역인 것 같아서 dto나 token쯤을 E2E에서 테스트해도 좋을 듯해요! 반영하지 않아도 됩니다 👍

2024-08-11 15:36 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +        }
isOwnedBy 메서드 생성해서 사용했습니다!

2024-08-11 15:39 UTC, JINU-CHANG approved these changes

2024-08-12 05:38 UTC, tsulocalize approved these changes

2024-08-12 05:38 UTC, merged