[BE] 체크리스트 질문조회 API를 수정한다.
woowacourse-teams/2024-bang-ggood pull request #307
Opened 2024-08-11 05:33 UTC by JINU-CHANG

## ❗ Issue

- #306 

## ✨ 구현한 기능

- 카테고리 및 질문 내용 변경
- 깨지는 테스트 수정

## 📢 논의하고 싶은 내용

## 🎸 기타

- 아직 디폴트 질문내용외에는 확정되지 않은 것 같아 월요일날 이야기하고 Question들은 더 추가해놓을게요~

2024-08-11 06:17 UTC, tsulocalize requested changes

2024-08-11 06:17 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
> +    SECURITY(6, "보안");
1,2,3,4로 가도 되지 않을까요?

2024-08-11 06:17 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
> +    WINDOW_7(7, Category.WINDOW, "환기가 잘 되는 구조인가요?", "창문의 크기와 방향을 확인하세요.", true),
window에 질문 하나 빠진 것 같은데 이미 논의된 사항인가요?

2024-08-11 06:17 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
> +    SECURITY_13(25, Category.SECURITY, "자취방의 보안 시설이 잘 갖추어져 있나요? (도어락, 창문 잠금장치 등)", null, true);
얘는 id가 다른 것 같아요!

2024-08-11 06:17 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/QuestionTest.java
> +                () -> assertThat(question.getCategory()).isEqualTo(Question.WINDOW_7.getCategory())
equals를 활용하면 한줄로도 가능할 것 같아요!

2024-08-11 08:33 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
> +    WINDOW_7(7, Category.WINDOW, "환기가 잘 되는 구조인가요?", "창문의 크기와 방향을 확인하세요.", true),
문장 수정할 부분이 있을 것 같아 월요일날 이야기해보고 넣으려고 했어요! 근데 지금 넣어도 상관없을 것 같아서 추가해놓을게요

2024-08-11 08:34 UTC, shin-jisong approved these changes
특별히 코멘트 남길 부분이 없어서 approve 합니다!

2024-08-11 08:34 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/QuestionTest.java
> +        int questionId = Integer.MAX_VALUE;
잘 바꿔 주셨네요 👍

2024-08-11 08:36 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
> +    SECURITY_13(25, Category.SECURITY, "자취방의 보안 시설이 잘 갖추어져 있나요? (도어락, 창문 잠금장치 등)", null, true);
예리하시군요 😮

2024-08-11 08:39 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/QuestionTest.java
> +                () -> assertThat(question.getCategory()).isEqualTo(Question.WINDOW_7.getCategory())
오! 반영했습니다~

2024-08-11 10:27 UTC, tsulocalize approved these changes

2024-08-11 15:32 UTC, tkdgur0906 reviewed
window 부분에 질문 빠진 것 월요일에 얘기해보고 이 pr에 추가하는게 좋을 것 같아 일단 approve는 안하겠습니다!
추가한 다음에 머지할게요!

2024-08-12 06:50 UTC, tsulocalize requested changes

2024-08-12 06:50 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
> -    @Test
좋아요 test가 삭제된 것 같아요!

2024-08-12 06:53 UTC, tkdgur0906 approved these changes

2024-08-12 06:53 UTC, tsulocalize approved these changes

2024-08-12 06:54 UTC, merged