[BE] 아티클 조회 API를 구현한다.
woowacourse-teams/2024-bang-ggood pull request #324
Opened 2024-08-12 07:43 UTC by tsulocalize

## ❗ Issue

- #314 

## ✨ 구현한 기능
- 아티클 조회 API

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-08-12 08:03 UTC, tkdgur0906 reviewed
간단한 질문만 남겼습니다!

2024-08-12 08:03 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
> +    ARTICLE_INVALID(HttpStatus.BAD_REQUEST, "해당 아티클이 존재하지 않습니다.");
invalid보다 not found에 가까운 것 같아요!

2024-08-12 08:53 UTC, shin-jisong approved these changes
수고하셨습니다! 간단한 질문만 남겼어요~

2024-08-12 08:53 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +        Article article = articleRepository.findById(id)
이건 repository에서 getById로 처리하기로 했던 부분 같아요!

2024-08-12 08:53 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +    @DisplayName("아티클 조회 실패 : 유효하지 않은 아이디인 경우")
E2E 테스트와 서비스 테스트를 구분 짓는 우주만의 기준이 궁금해요~ 
서비스 테스트와 중복되는 테스트길래 여쭤봅니다

2024-08-12 08:58 UTC, JINU-CHANG requested changes

2024-08-12 08:58 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +        Article article = articleRepository.findById(id)
이 부분은 getById() 로 하는 어떤가요?

2024-08-12 08:58 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +        long articleId = 1L;
더미로 데이터 넣어 사용하는 건 어떨까요?

2024-08-12 08:58 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +                .statusCode(400);
에러 메시지까지 검증해주면 좋을 것 같아요!

2024-08-12 09:31 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/ArticleResponseDto.java
> +public record ArticleResponseDto(Long id, String title, String content) {
수정했습니다!

2024-08-12 09:33 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +        Article article = articleRepository.findById(id)
수정했습니다!

2024-08-12 09:33 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +        Article article = articleRepository.findById(id)
수정했습니다!

2024-08-12 09:34 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
> +    ARTICLE_INVALID(HttpStatus.BAD_REQUEST, "해당 아티클이 존재하지 않습니다.");
수정했습니다!

2024-08-12 09:39 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +        long articleId = 1L;
데이터를 넣어 테스트하도록 수정했습니다!

2024-08-12 09:44 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +    @DisplayName("아티클 조회 실패 : 유효하지 않은 아이디인 경우")
제 기준은 Controller가 단순 전달 로직만 있다면 E2E 테스트는 필요 없다고 생각합니다.
다만, 현재 저희 팀에서 모든 API에 대해 E2E 테스트를 진행하고 있다고 파악해 테스트 케이스를 추가했습니다!

2024-08-12 09:45 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +                .statusCode(400);
메시지 검증 추가했습니다!

2024-08-13 01:01 UTC, JINU-CHANG approved these changes

2024-08-13 01:09 UTC, tkdgur0906 approved these changes

2024-08-13 01:09 UTC, merged