[BE] 체크리스트 좋아요 필터링 기능을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #370
Opened 2024-08-15 06:20 UTC by tkdgur0906

## ❗ Issue

-  #298

## ✨ 구현한 기능

- 체크리스트 리스트 좋아요 필터링 기능

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-08-15 06:38 UTC, shin-jisong reviewed
수고하셨습니다 카피~~

2024-08-15 06:38 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
> +    public ResponseEntity<UserChecklistsPreviewResponse> readLikedUserChecklistsPreview(@AuthPrincipal User user) {
위에 명명과 통일성을 지키기 위해 맞추신 것 같기는 하지만 User는 파라미터에도 명시되어 있어서 불필요한 단어 같아요! 카피는 어떻게 생각하시나요?

2024-08-15 06:38 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
> +    @Query("SELECT c FROM Checklist c "
가독성이 더 좋아졌네요! 👍

2024-08-15 07:48 UTC, JINU-CHANG requested changes
잘 구현해주셨네요!! 수고하셨습니다 👍

2024-08-15 07:48 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
>      public static final ChecklistLike CHECKLIST_LIKE_1 = new ChecklistLike(CHECKLIST1_USER1);
```suggestion
    public static final ChecklistLike CHECKLIST1_LIKE_1 = new ChecklistLike(CHECKLIST1_USER1);
```
어떤 체크리스트의 좋아요인지 네이밍에 드러나면 좋을 것 같아요!

2024-08-15 07:48 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +                () -> assertThat(checklists.get(1).checklistId()).isEqualTo(2)
```suggestion
     () -> assertThat(checklists.get(0).checklistId()).isEqualTo(ChecklistFixture.CHECKLIST1_USER1.getId()),
     () -> assertThat(checklists.get(1).checklistId()).isEqualTo(ChecklistFixture.CHECKLIST2_USER1.getId())
```

Checklist에서 id를 꺼내와서 확인하는게 더 안전할 것 같아요~

2024-08-15 07:48 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
> +    List<Checklist> findAllByUserAndIsLiked(@Param("user") User user);
해당 메서드에 대한 테스트도 있으면 좋을 것 같아요!

2024-08-15 08:37 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +                () -> assertThat(checklists.get(1).checklistId()).isEqualTo(2)
id가 같다면 equals()를 쓰는 게 더 좋을 것 같네요

2024-08-15 08:37 UTC, tsulocalize approved these changes

2024-08-16 04:59 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
> +    public ResponseEntity<UserChecklistsPreviewResponse> readLikedUserChecklistsPreview(@AuthPrincipal User user) {
동의합니다! User를 안붙이는게 더 자연스러울 것 같아요!
다른 메서드 명명도 동일하게 수정했습니다~

2024-08-16 05:19 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +                () -> assertThat(checklists.get(1).checklistId()).isEqualTo(2)
`readLikedChecklistsPreview`의 반환타입이 dto라 기존 Fixture랑 equals가 안돼서 id로 비교했습니다!

2024-08-16 05:39 UTC, shin-jisong approved these changes

2024-08-16 05:58 UTC, JINU-CHANG approved these changes

2024-08-16 06:10 UTC, merged