아티클 추가 삭제 기능 api를 구현한다.
woowacourse-teams/2024-bang-ggood pull request #389
Opened 2024-08-16 08:09 UTC by tsulocalize

## ❗ Issue

- #384 

## ✨ 구현한 기능
- 아티클 추가 api 구현
- 아티클 삭제 api 구현
- 아티클 도메인 수정(키워드, 요약)
- response 일부 변경

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-08-16 08:29 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
> +        Long id = articleService.createArticle(request);
long으로 받는 것은 어떤가요?

2024-08-16 08:35 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +    public Long createArticle(ArticleCreateRequest request) {
여기서 long을 반환해도 좋을 것 같아요!

2024-08-16 08:39 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +                .isEqualTo("제목");
제목 대신 ARTICLE_CREATE_REQUEST 값을 꺼내와도 좋을 것 같아요!

2024-08-16 08:40 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +        Article article1 = new Article("제목1", "내용1", "키워드1", "요약1");
Fixture로 빼도 좋을 것 같아요!

2024-08-16 08:40 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +        articleRepository.save(article1);
saveAll로 한번에 저장하는건 어떤가요?

2024-08-17 06:39 UTC, JINU-CHANG requested changes
수고하셨습니다~ 👍

2024-08-17 06:39 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +    public ArticlesDetailPreviewResponse readArticles() {
`@Transactional` 빠진 것 같네요!

2024-08-17 06:39 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +                .statusCode(401);
에러 메시지 확인해주면 좋을 것 같아요!

2024-08-17 06:39 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +        articleRepository.save(ARTICLE);
모든 메서드에 `articleRepository.save(ARTICLE);`가 있어서 beforeEach로 빼도 좋을 것 같아요~

2024-08-17 06:39 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/repository/ArticleRepository.java
> +    List<Article> findLatestTop3();
limit 개수를 service에서 받아오는 건 어떨까요?? 그리고 Repository 관련 테스트도 필요할 것 같아요!
```suggestion
    @Query("SELECT a FROM Article a WHERE a.deleted = false ORDER BY a.createdAt DESC LIMIT :count")
    List<Article> findLatestTop3(@Param("count") count);
```

2024-08-17 14:17 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +    public ArticlesDetailPreviewResponse readArticles() {
추가했습니다!

2024-08-17 14:19 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +        articleRepository.save(ARTICLE);
반영했습니다!

2024-08-17 14:30 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +        articleRepository.save(article1);
saveAll로 저장하면 timeStamp 차이가 미세해서 반복 테스트 시 가끔 fail되는 문제가 발생합니다!

2024-08-17 14:32 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +        Article article1 = new Article("제목1", "내용1", "키워드1", "요약1");
저는 해당 메서드에서만 사용되는 객체는 Fixture를 사용하지 않는 게 더 좋아보이는데 어떻게 생각하시나요?

2024-08-17 14:32 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +                .isEqualTo("제목");
반영했습니다!

2024-08-17 14:37 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +                .statusCode(401);
반영했습니다!

2024-08-18 06:26 UTC, shin-jisong requested changes
수고하셨습니다 우주~~

2024-08-18 06:26 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
> +    public ResponseEntity<ArticlesDetailPreviewResponse> readArticles() {
왜 명명에 detail이 추가됐나요?! 충돌하는 이름인 것 같아 여쭤봅니다

2024-08-18 06:26 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/repository/ArticleRepository.java
> +    @Query("SELECT a FROM Article a WHERE a.id = :id AND a.deleted = false")
사소한 부분이지만 SQL 문에 적당한 개행을 추가하면 가독성이 올라갈 것 같아요!

2024-08-18 06:26 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +    public static final int MAX_ARTICLE_CARDS = 3;
외부에서 사용하지 않는다면 private을 사용해도 될 것 같네요~

2024-08-18 06:26 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +    @DisplayName("아티클 생성 실패: 유저가 아닌 경우")
제목이 없는 경우 에러 메시지가 DTO에 있었던 걸로 기억하는데 이런 부분들을 ETE 테스트에서 해 보면 어떨까요?

2024-08-18 06:26 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +        Article article1 = new Article("제목1", "내용1", "키워드1", "요약1");
저는 Fixture의 목표가 재사용도 있지만 테스트에서 중요하지 않는 로직은 테스트에서 분리하고 테스트하고자 하는 부분만 보여 준다는 의의도 있다고 생각하여 fixture로 분리해도 좋다고 생각해요!

2024-08-18 06:26 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +        assertThat(articleTitles).containsExactly("제목4", "제목3", "제목2");
해당 객체의 getter를 쓰는 게 테스트의 견고함을 더해 줄 것 같아요!

2024-08-19 05:04 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
> +    public ResponseEntity<ArticlesDetailPreviewResponse> readArticles() {
기획에서 아티클 프리뷰 형태가 2가지로 제공되야 한다고 합니다!
하여, 현재 `preview`, `detailPreview`를 분리하여 보았습니다

2024-08-19 05:04 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +    public static final int MAX_ARTICLE_CARDS = 3;
맥북으로 바꿨더니 단축키 설정 미스가... 수정했습니다!

2024-08-19 05:09 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/repository/ArticleRepository.java
> +    @Query("SELECT a FROM Article a WHERE a.id = :id AND a.deleted = false")
반영했습니다!

2024-08-19 05:22 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
> +    @DisplayName("아티클 생성 실패: 유저가 아닌 경우")
테스트 추가했습니다!

2024-08-19 05:26 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +        assertThat(articleTitles).containsExactly("제목4", "제목3", "제목2");
반영했습니다!

2024-08-19 05:27 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
> +        Article article1 = new Article("제목1", "내용1", "키워드1", "요약1");
반영했습니다!

2024-08-19 05:51 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/repository/ArticleRepository.java
> +    List<Article> findLatestTop3();
반영했습니다!

2024-08-19 05:56 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
> +        Long id = articleService.createArticle(request);
Repository 상위 메서드 오버라이드 문제로 Long으로 통일하는 게 좋을 것 같습니다!

2024-08-19 05:58 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +    public Long createArticle(ArticleCreateRequest request) {
반영했습니다!

2024-08-19 06:18 UTC, tkdgur0906 approved these changes

2024-08-19 07:21 UTC, JINU-CHANG approved these changes
수고하셨습니다~

2024-08-19 07:21 UTC, shin-jisong approved these changes

2024-08-19 07:21 UTC, merged