[BE] 로그아웃 기능을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #457
Opened 2024-08-20 06:24 UTC by tkdgur0906

## ❗ Issue

- #405 

## ✨ 구현한 기능

- 로그아웃 시 토큰 블랙리스트에 저장

## 📢 논의하고 싶은 내용

## 🎸 기타
- 임시방편으로 메모리에 블랙리스트를 저장하였습니다. 추후 refresh token을 도입하면 전체적인 수정이 필요하여 간단하게 구현하였습니다.

2024-08-20 06:47 UTC, tsulocalize approved these changes
고군분투하셨습니다!

2024-08-20 06:47 UTC, healim01 commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
> +    @DisplayName("인증 실패 : 블랙리스트에 들어간 토큰일 경우")
쿠키 제거,, 가능한가요??

2024-08-20 06:50 UTC, shin-jisong approved these changes
수고하셨습니다~~

2024-08-20 06:50 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
> +    AUTHENTICATION_TOKEN_IN_BLACKLIST(HttpStatus.UNAUTHORIZED, "이미 로그아웃되어 블랙리스트에 존재하는 토큰입니다. 다시 로그인 해주세요."),
프론트엔드에서 에러 메시지를 볼 때 해당 메시지를 보면 의미하는 바를 명확하게 모를 것 같아요! 블랙리스트는 서버 내부적으로만 사용하고 해당 명명을 유출시키지 않는 게 어떨까요~?

2024-08-20 06:50 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private static final Set<String> blackList = new HashSet<>();
해당 부분을 시간과 구현 사이 적절한 지점에서 구현하셨네요! 혹시 개선한다면 어떤 방향이 좋을지 생각해 두신 게 있을까요?

2024-08-20 06:50 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    public boolean isAccessTokenInBlackList(String accessToken) {
혹시 BlackList보다 더 적절한 명명이 없을까요? 예를 들어 ExpiredTokens 같은 명명도 좋을 듯하다 생각해요 보안적으로 통용되는 명명이라면 BlackList도 적절한 것 같아요!

2024-08-20 06:50 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
> +    @DisplayName("인증 실패 : 블랙리스트에 들어간 토큰일 경우")
테스트를 적절하게 수행해 주셨네요 👍

2024-08-20 07:04 UTC, JINU-CHANG requested changes
카피 수고많으셨어요~!!

2024-08-20 07:04 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthPrincipalArgumentResolver.java
> +
extractUser 내부에서 해당 로직을 처리하면 어떨까요? extractUser를 사용할 때도 검증이 필요할 것 같아서 합치면 좋을 것 같아요

2024-08-20 07:04 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
> +                                       @RequestHeader(value = "Cookie") String accessToken) {
user와 accessToken의 유저가 같은지 검증하는 로직 추가되면 좋을 것 같습니다~

2024-08-20 08:44 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private static final Set<String> blackList = new HashSet<>();
추후에 refresh token을 도입하면 db 혹은 redis에 저장하는 방식으로 개선할 것 같습니다!
자세한 과정은 같이 얘기해봐야할 것 같아요!

2024-08-20 08:49 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    public boolean isAccessTokenInBlackList(String accessToken) {
다른 명명도 고려해봤는데 일반적으로 통용되기도 하고 명확하게 표현될 것 같아 유지했습니다!

2024-08-21 02:42 UTC, JINU-CHANG approved these changes

2024-08-21 02:42 UTC, merged