[BE] 질문 조회시 하이라이트를 함께 전달한다.
woowacourse-teams/2024-bang-ggood pull request #467
Opened 2024-08-20 12:07 UTC by JINU-CHANG

## ❗ Issue

- #466 

## ✨ 구현한 기능

- 질문 내부 하이라이트 데이터 저장
- Question 클래스 변경
- 질문 조회시 하이라이트 키워드 함께 전달

## 📢 논의하고 싶은 내용

QuestionResponse 타입을 record에서 class로 변경했습니다 ‼️
현재 CustomChecklistQuestionResponse, QuestionResponse, SelectedQuestionResponse가 QuestionResponse의 필드를 공유하고 있는데요, Question의 필드가 추가될 때마다 모든 DTO를 변경해줘야하는 것이 불편하게 느껴졌습니다. Question 데이터는 필드 변경될때마다 다른 DTO들이 모두 영향을 받을 것 같아서 연관관계가 강하다고 생각했고 이를 상속으로 풀어서 해결했습니다. Record 사용이 컨벤션이지만 이렇게 필요한 부분은 클래스로 사용해도 괜찮을지 다같이 논의해보면 좋을 것 같아요~

## 🎸 기타

2024-08-20 13:16 UTC, tsulocalize requested changes

2024-08-20 13:16 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedQuestionResponse.java
> +public class SelectedQuestionResponse extends QuestionResponse {
`@Jsonunwrapped`를 활용하는 건 어떨까요?
연관관계가 강해 상속으로 해결했다는 건 잘 이해가지 않는 것 같아요?

2024-08-20 13:16 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
> +                .statusCode(200);
깨지는 테스트를 수정하는 건 좋지만, 기존에 테스트하고 있던 내용은 보존해야하지 않을까요?
(왜 깨지는 건가요?)

2024-08-20 13:16 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
>      }
코드 무결성을 위해 title이 highlights 단어를 모두 포함하고 있다는 validate를 추가하는 건 어떨까요?

2024-08-21 00:49 UTC, shin-jisong reviewed
수고하셨습니다! response와 같은 dto는 변화에 가장 맞닿아 있는 부분이라 생각해서 많이 바뀌는 게 어쩔 수 없다고 생각해요 상속을 사용하면 오히려 보이는 데이터 쪽이 유연하지 못할 수도 있다는 생각인데 해당 문제가 생기면 분리해도 될 것 같기는 하네요!

2024-08-21 00:49 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
>  class ChecklistE2ETest extends AcceptanceTest {
이런 부분은 주석으로 처리한 후 TODO로 남겨 두면 좋을 것 같아요!

2024-08-21 01:18 UTC, tkdgur0906 approved these changes

2024-08-21 01:18 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
> +                .statusCode(200);
일단 주석처리해도 좋을듯요!

2024-08-21 01:23 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedQuestionResponse.java
> +public class SelectedQuestionResponse extends QuestionResponse {
QuestionResponse를 상속받으면 공통 필드를 하나의 클래스로 관리할 수 있을 것 같아요!

`@Jsonunwrapped` 와 record를 함께 사용하는 방식은 조금 복잡한 것 같아서 우선 상속으로 처리해두고 방법을 좀 더 찾아볼게요

2024-08-21 02:21 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
>      }
반영했습니다!

2024-08-21 02:24 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
>  class ChecklistE2ETest extends AcceptanceTest {
우주 질문에 답변 남겨놨습니다~ 혹시 추가 의견있으면 말씀해주세요!

2024-08-21 02:29 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
> +                .statusCode(200);
extract()를 사용하면 `기본생성자와 setter`가 필요하더라구요! 지금까지는 Record를 사용해서 문제가 없었지만, class를 사용하면 모두 정의해주어야하는데요, 이를 위해 생성자3개를 추가하고 setter를 퍼블릭으로 열어놓는게 맞나..?라는 생각이 들었습니다.
그리고 해당 테스트도 제가 작성했던 테스트인데 다시보니 서비스에서 검증가능하다고 생각해서 삭제했습니다!

2024-08-21 02:36 UTC, shin-jisong approved these changes

2024-08-21 02:48 UTC, tsulocalize approved these changes
고군분투하셨습니다!

2024-08-21 02:48 UTC, merged