카테고리 조회 기능을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #48
Opened 2024-07-22 06:25 UTC by JINU-CHANG

## ❗ Issue

- #46

## ✨ 구현한 기능

- 카테고리 조회 기능을 구현했습니다.

## 📢 논의하고 싶은 내용

- 테스트 코드 수정되거나 추가할 부분 없는지 확인해주세요.

## 🎸 기타

2024-07-22 06:51 UTC, shin-jisong approved these changes
특별한 코멘트할 사항이 보이지 않아 approve 합니다! 
수고하셨습니다 👍

2024-07-22 06:58 UTC, tkdgur0906 requested changes

2024-07-22 06:58 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
> +    private final Integer id;
여기에 int 대신 Integer를 사용하신 이유가 있나요?

2024-07-23 01:33 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
> +    private final Integer id;
null일 필요가 없으니 Int로 변경하는게 좋겠네요! 수정하겠습니다.

2024-07-23 01:50 UTC, tkdgur0906 approved these changes
반영하신거 확인했습니다!
머지하겠습니다😀

2024-07-23 01:50 UTC, merged