[BE] 가까운 지하철 역을 2개 보여준다.
woowacourse-teams/2024-bang-ggood pull request #575
Opened 2024-09-10 02:45 UTC by tsulocalize

## ❗ Issue

- #574 

## ✨ 구현한 기능
- 지하철 역을 2개 보여주는 기능
- 환승역을 하나로 보여주는 기능

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-09-17 16:08 UTC, tkdgur0906 requested changes
고생많으셨습니다!
리뷰 한번 확인해주세요~

2024-09-17 16:08 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
> +    private static final int MAX_NESTING_STATION_NUMBER = 4;
중첩된 지하철역 수가 4인 이유가 있나요?

2024-09-17 16:08 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
>                      return SubwayStationResponse.of(station, (int) Math.round(distance / AVERAGE_WALKING_SPEED));
거리 계산 로직을 메서드 분리하면 좋을 것 같아요!

2024-09-17 16:08 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
> +    public List<SubwayStationResponse> readNearestStation(double latitude, double longitude) {
스트림이 길어서 가독성이 좀 떨어진다고 생각하는데, 인지 단위로 한번씩 끊는 것은 어떤가요?

2024-09-17 16:08 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/station/SubwayStationServiceTest.java
> +    void readNearestStation(double latitude, double longitude, Station nearestStation, Station nextNearestStation) {
테스트 코드를 맨 위로 올리는 것은 어떤가요?

2024-09-19 02:09 UTC, JINU-CHANG requested changes

2024-09-19 02:09 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/controller/SubwayStationController.java
> +                                                                          @RequestParam("longitude") double longitude) {
Double로 바꿔야 될 것 같아요!

2024-09-19 02:09 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/SubwayStationResponse.java
> +        stationLine.add(station.getLine());
어차피 1개만 받는 것 같은데 왜 List를 선택하셨나요??

2024-09-19 03:55 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/SubwayStationResponse.java
> +        stationLine.add(station.getLine());
merge() 메서드를 통해 다른 Response와 합치기 위함입니다.
```
잠실역 2호선.merge(잠실역 8호선) = 잠실역 2호선,8호선
```

2024-09-19 03:56 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/controller/SubwayStationController.java
> +                                                                          @RequestParam("longitude") double longitude) {
반영했습니다!

2024-09-19 04:07 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/SubwayStationResponse.java
> +            throw new BangggoodException(ExceptionCode.STATION_NOT_SAME);
반영했습니다!

2024-09-19 04:08 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/station/SubwayStationServiceTest.java
> +    void readNearestStation(double latitude, double longitude, Station nearestStation, Station nextNearestStation) {
반영했습니다!

2024-09-19 04:13 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
>                      return SubwayStationResponse.of(station, (int) Math.round(distance / AVERAGE_WALKING_SPEED));
반영했습니다!

2024-09-19 04:13 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
> +    private static final int MAX_NESTING_STATION_NUMBER = 4;
대한민국 내 환승역 최대 중첩수가 4 입니다!

2024-09-19 04:28 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
> +    public List<SubwayStationResponse> readNearestStation(double latitude, double longitude) {
반영했습니다!

2024-09-20 00:35 UTC, shin-jisong requested changes
간단한 리뷰만 남겼습니다! 수고하셨습니다~

2024-09-20 00:35 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
> +    public double getDistance(double latitude, double longitude) {
getXX의 명명은 getter와 혼동되는 것 같은데 함수의 명명을 바꿔보는 것 어떨까요?

2024-09-20 04:28 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
> +    public double getDistance(double latitude, double longitude) {
calculateDistance로 바꿨습니다!

2024-09-20 08:50 UTC, tkdgur0906 approved these changes
고생하셨습니다~

2024-09-20 10:55 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/controller/SubwayStationController.java
> +                                                                          @RequestParam("longitude") double longitude) {
Service 쪽도 확인해주세요!

2024-09-20 11:07 UTC, JINU-CHANG requested changes

2024-09-20 11:07 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
> +                .limit(MAX_NESTING_STATION_NUMBER * REQUESTED_STATION_NUMBER)
이 부분은 어떤 의미의 코드인가요??

2024-09-20 11:07 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
>                      return SubwayStationResponse.of(station, (int) Math.round(distance / AVERAGE_WALKING_SPEED));
SubwayStation 클래스에 walkingTime 계산을 요청할 수도 있지 않을까요?
뒤에 `(int) Math.round(distance / AVERAGE_WALKING_SPEED));` 로직과 따로 있지 않아도 될 것 같아요

2024-09-20 11:07 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
> +                ));
이 부분만 조금 더 개선하면 이해하기 쉬울 것 같아요!

2024-09-21 06:58 UTC, shin-jisong approved these changes
수고하셨습니다!

2024-09-23 04:55 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
> +                .limit(MAX_NESTING_STATION_NUMBER * REQUESTED_STATION_NUMBER)
가장 가까운 역 목록을 가져올 때 환승역이 있을 수 있기 때문에, 가져올 때 최대 환승역 수를 포함한 것입니다.
예를 들어, `잠실 2호선 - 잠실 8호선 - 잠실새내 2호선 -...` 이런 식으로 이어진다고 할 때 가장 가까운 역 2개를 가져온다고 하면
같은 역인 [잠실 2호선, 잠실 8호선]으로 나올 수 있기 때문이죠.

2024-09-23 05:02 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
>                      return SubwayStationResponse.of(station, (int) Math.round(distance / AVERAGE_WALKING_SPEED));
반영했습니다!

2024-09-23 05:19 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
> +                ));
메서드 분리를 통해 이해하기 쉽게 만들어주었습니다!

2024-09-23 06:24 UTC, merged