[BE] 커스텀 체크리스트 서비스를 분리한다.
woowacourse-teams/2024-bang-ggood pull request #580
Opened 2024-09-10 08:32 UTC by tsulocalize

## ❗ Issue

- #576 

## ✨ 구현한 기능
커스텀 체크리스트 -> ChecklistQuestionService로 이동

## 📢 논의하고 싶은 내용
`체크리스트 질문 조회` API가 정확히는 `커스텀 체크리스트 질문 조회`여서 클래스는 변경 했는데, 엔드포인트는 일단 남겨놨습니다.
나중에 `커스텀` 명칭 수정되면 엔드포인트도 수정해야 될 것 같아요.

## 🎸 기타

2024-09-10 12:55 UTC, JINU-CHANG requested changes
수고하셨습니다 👍

2024-09-10 12:55 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
> +@Service
메서드에 `@Transactional` 어노테이션이 붙어있지 않아요 🥲
계속 이 부분을 놓치는 것 같은데 아래처럼 두고 필요한 메서드에만 @Transactioanl 어노테이션 붙이는 걸 컨벤션으로 지정하면 좋을 것 같은데 다른 분들의 의견은 어떤가요?
```
@Transactioanl(readOnly = true)
@Service
public class QuestionManageService {
}
```

2024-09-10 12:55 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
> +    }
- 지금 단계에서 이 부분 리팩토링하고 가면 좋을 것 같아요! 적당히 분리가 필요해 보여요 🤔
- 아래 categorizeAllQuestionWithSelected()와 비슷해보이는데 하나는 Map, 하나는 for문으로 구현되어있네요. 방식을 통일해서 리팩토링하면 어떨까요?

2024-09-10 12:55 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
> +        return new CategoryCustomChecklistQuestionsResponse(response);
저희 DTO에는 정팩매 사용하기로 한걸로 기억하는데 그러면 이부분도 수정하면 좋을 것 같아요!

2024-09-10 13:05 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
> +    }
제가 맡은 부분이었군요 ㅎㅎ..

2024-09-11 00:44 UTC, tkdgur0906 approved these changes

2024-09-11 05:32 UTC, shin-jisong approved these changes
수고하셨습니다~

2024-09-11 05:35 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
> +        return new CategoryCustomChecklistQuestionsResponse(response);
반영했습니다!

2024-09-11 05:35 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
> +@Service
반영했습니다!

2024-09-11 05:35 UTC, merged