[BE] 체크리스트 좋아요 서비스 구조를 분리한다.
woowacourse-teams/2024-bang-ggood pull request #607
Opened 2024-09-17 15:01 UTC by tkdgur0906

## ❗ Issue

- #578 

## ✨ 구현한 기능

- 체크리스트 좋아요 관련 기능 서비스 구조 변경

## 📢 논의하고 싶은 내용

체크리스트 목록 좋아요 필터링 기능을 다음과 같은 순서로 구현하려고 시도했습니다.
1. 사용자의 체크리스트 좋아요 목록 조회
2. 해당 좋아요 목록으로 체크리스트 목록 조회

하지만 ChecklistLike가 User를 가지고 있지 않아 Checklist, User와 join을 해야했습니다.
그런 방식으로 구현하기 보다 기존 코드를 그대로 가져가는게 좋을 것 같아 유지했습니다.
다른 의견 있으시면 말씀해주세요!

## 🎸 기타

2024-09-19 12:01 UTC, tsulocalize approved these changes
크나큰 업적 이루셨습니다!

2024-09-19 13:53 UTC, JINU-CHANG requested changes
논의하고 싶은 내용에 적힌 내용이 ChecklistRepository의 findAllByUserAndIsLiked 관련 내용이죠? 저는 좋은 것 같습니다 이 방식이 더 직관적이고 이해하기 쉬운 것 같아요 👍

카피 수고많으셨습니다 😃

2024-09-19 13:53 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
> +    }
메서드가 2개면 굳이 묶을 필요없다고 생각해요! createLike() 내에 두면 파악이 좀 더 쉬울 것 같아요~

2024-09-19 13:53 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
> +        ChecklistLike checklistLike = checklistLikeRepository.getByChecklistId(checklist.getId());
repository 메서드 파라미터 타입 long -> Long으로 변경부탁드려요 !

2024-09-19 13:53 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
> +                () -> assertThat(response.checklists().size()).isEqualTo(2),
```suggestion
                () -> assertThat(response.checklists().size()).hasSize(2),
```

2 상수로 빼면 좋을 것 같아요!

2024-09-19 13:53 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/like/controller/ChecklistLikeE2ETest.java
> +    @DisplayName("체크리스트 좋아요 추가 성공")
테스트 꼼꼼하게 작성해주셨네요 👍👍

2024-09-20 00:41 UTC, shin-jisong requested changes
카피 꼼꼼히 해 주셔서 리뷰할 게 많지 않네요! ㅎㅎ

2024-09-20 00:41 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> +import com.bang_ggood.checklist.dto.response.UserChecklistPreviewResponse;
저희가 체크리스트 공유 기능이 있지 않고, 체크리스트에 유저 정보가 포함되지 않을 일이 없는데 user 명명을 쓴 이유가 궁금해요!

2024-09-20 00:41 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/like/controller/ChecklistLikeController.java
> +@RestController
작업량이 꽤나 많았겠네요 수고하셨습니다 👍

2024-09-20 08:51 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
> +    }
넵 반영했습니다~

2024-09-20 10:01 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> +import com.bang_ggood.checklist.dto.response.UserChecklistPreviewResponse;
예전에 사용하던거 그대로 사용했는데, User 빼도 좋을 것 같아서 이름 변경했습니다!

2024-09-20 11:08 UTC, JINU-CHANG approved these changes

2024-09-21 06:59 UTC, shin-jisong approved these changes
제가 마지막 approve네요! 머지하겠습니다 🍀

2024-09-21 06:59 UTC, merged