[BE] 아티클에 대표이미지를 추가한다.
woowacourse-teams/2024-bang-ggood pull request #612
Opened 2024-09-19 02:49 UTC by tsulocalize

## ❗ Issue

- #601 

## ✨ 구현한 기능
아티클 내 thumbnail 추가
DB 구조 변경

## 📢 논의하고 싶은 내용
API 엔드포인트 바꿨는데 괜찮은지 한번 봐주세요~

## 🎸 기타

2024-09-19 07:57 UTC, tkdgur0906 approved these changes
고생하셨습니닷

2024-09-20 00:46 UTC, shin-jisong approved these changes
수고하셨습니다~ 👍

2024-09-20 00:46 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
> +    @GetMapping("/articles/detail")
전의 명명이 더 나은 것 같은데 바꾼 이유가 궁금해요!

2024-09-20 05:16 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
> +    @GetMapping("/articles/detail")
1. 모든 아티클 조회 API가 최신순으로 불러오기 때문에 latest가 불필요하다고 생각했습니다!
2. 일반 목록과 디테일 목록의 엔드포인트를 명확히 분리해주고 싶었습니다!

2024-09-20 11:15 UTC, JINU-CHANG requested changes

2024-09-20 11:15 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
> +    public ResponseEntity<ArticlesDetailPreviewResponse> readArticlesDetail() {
Detail과 Preview는 반대되는 개념이라고 생각하는데요,, 일반 목록과 디테일 목록이 어떻게 다른거죠?-?

2024-09-20 11:15 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +        List<ArticleDetailPreviewResponse> articles = articleRepository.findLatest().stream()
```suggestion
        List<ArticleDetailPreviewResponse> articles = articleRepository.findLatestArticles().stream()
```

2024-09-21 07:03 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
> +    public ResponseEntity<ArticlesDetailPreviewResponse> readArticlesDetail() {
저도 detail 명명이 하나를 세부적으로 본다는 것으로 느껴져서 preview와는 대치되는 개념이라 느껴져요!
Partial 등 일부분을 뜻하는 용어를 사용하거나 List 명명을 선택하는 것이 좋을 듯합니다

2024-09-23 05:33 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
> +    public ResponseEntity<ArticlesDetailPreviewResponse> readArticlesDetail() {
DTO 명 수정해주었습니다!

2024-09-23 05:38 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
> +        List<ArticleDetailPreviewResponse> articles = articleRepository.findLatest().stream()
반영했습니다!

2024-09-23 07:37 UTC, merged