[BE] 새로운 질문을 추가한다.
woowacourse-teams/2024-bang-ggood pull request #620
Opened 2024-09-20 10:41 UTC by tkdgur0906

## ❗ Issue

- #619 

## ✨ 구현한 기능

- 체크리스트 질문 추가 및 수정

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-09-20 11:16 UTC, JINU-CHANG approved these changes
수고하셨습니다~

2024-09-21 07:08 UTC, shin-jisong approved these changes
수고하셨습니다~

2024-09-22 17:21 UTC, tsulocalize requested changes

2024-09-22 17:21 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
> +    ROOM_CONDITION_3(3, Category.ROOM_CONDITION, "벌레가 나온 흔적 없이 깔끔한가요??", "벌레 퇴치약이 부착되어 있는지 확인하세요.", List.of("벌레"),
여기 물음표 2개입니당!

2024-09-23 12:16 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
> +    ROOM_CONDITION_3(3, Category.ROOM_CONDITION, "벌레가 나온 흔적 없이 깔끔한가요??", "벌레 퇴치약이 부착되어 있는지 확인하세요.", List.of("벌레"),
반영했습니다!

2024-09-23 13:28 UTC, tsulocalize approved these changes

2024-09-23 13:28 UTC, merged