[BE] 로그인하지 않은 사용자도 특정 페이지에 접근할 수 있도록 권한을 허용한다.
woowacourse-teams/2024-bang-ggood pull request #625
Opened 2024-09-21 10:43 UTC by JINU-CHANG

## ❗ Issue

- #622 

## ✨ 구현한 기능

- [x] User엔티티에 UserType 추가
- [x] 게스트 유저의 체크리스트와 질문들 추가
- [x] 게스트 유저일 때 허용할 API를 리스트업한 후 작업
  - [x] /custom-checklist/all
  - [x] /checklists/questions
  - [x] /checklists
  - [x] /articles/{id}
  - [x] /articles
  - [x] /articles/detail
- [x] 게스트 유저일 때 접근할 수 없는 API를 리스트업한 후 작업
- [x] ArgumentResolver 테스트 추가

## 📢 논의하고 싶은 내용

## 🎸 기타

- 변경사항이 많으니 꼼꼼하게 확인해주세요!

**코드 설명사항**
- User 도메인에 UserType 필드를 추가했습니다. UserType은 ADMIN, USER, GUEST입니다.
- DBInitializer클래스는 스프링부트 실행 이후 게스트 유저와 게스트유저의 디폴트 체크리스트, 디폴트 커스텀 체크리스트 질문을 생성합니다.
- `@UserPrincipal`이라는 새로운 어노테이션과 ArgumentResolver가 추가됐습니다. 로그인하지 않은 사용자가 해당 API를 호출하면 GuestUser가 할당됩니다.
- 기존 코드를 최대한 유지하고 서비스 클래스내의 변경사항을 적게하기 위해 해당 방식으로 구현하게 되었습니다.

2024-09-22 13:42 UTC, tkdgur0906 requested changes
제제 그녀는 신인가..
완전 야무지게 바꿔주셨네요!
아주아주 고생많으셨습니다~~

2024-09-22 13:42 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
> +    public ResponseEntity<CustomChecklistQuestionsResponse> readCustomChecklistQuestions(@UserPrincipal User user) {
QuestionController 말고 `/checklists`나 `/checklists/{id}` 같은 api도 UserPrincipal이 필요하지 않나용?

2024-09-22 13:42 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/CookieResolverTest.java
> +        cookies[0] = new Cookie(CookieProvider.TOKEN_COOKIE_NAME, expectedToken);
```suggestion
        Cookie[] cookies = { new Cookie(CookieProvider.TOKEN_COOKIE_NAME, expectedToken) };

```

선언할 때 할당할 수도 있을 것 같아요!

2024-09-22 13:42 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthPrincipalArgumentResolver.java
> +        String token = cookieResolver.extractToken(request.getCookies());
위에서 null 처리하고 extractToken에서 같은 에러 처리를 하고 있는데, 안정성을 위해 2번 작성하신건가요?

2024-09-22 17:18 UTC, tsulocalize requested changes

2024-09-22 17:18 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
> +                && Objects.equals(email, user.email) && type == user.type;
entity에 대한 equals는 id 비교로 충분하지 않을까요?

2024-09-22 17:18 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +        return userRepository.getUserByType(UserType.GUEST);
UserType.Guest인 데이터가 2개 있으면 어떻게 될까요?

2024-09-22 17:18 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/DefaultChecklistService.java
> +    }
(아래 2개 포함) 값이 변하지 않는데 왜 새 객체를 만들어주는 건가요?

2024-09-22 17:18 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipal.java
> +public @interface UserPrincipal {
AuthPrincipal과 UserPrincipal이 헷갈리는 것 같은데 잘 구분해줄 방법은 없을까요?

2024-09-23 04:59 UTC, shin-jisong requested changes
수정이 까다로우셨을 것 같아요! 수고하셨습니다 최고 👍

2024-09-23 04:59 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/DBInitializer.java
> +    private final UserRepository userRepository;
Repostiory와 Service를 같은 레벨에서 호출하고 있네요!
userService를 사용하는 건 어떨까요?

2024-09-23 04:59 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/DefaultChecklistService.java
> +    private final ChecklistManageService checklistManageService;
Service가 3계층으로 되었네요!` DefaultChecklistService - ChecklistManageService - ChecklistService`
checklistManageService 내부에 함수를 작성하는 건 어떤가요?

2024-09-23 04:59 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/UserType.java
> +    ADMIN, USER, GUEST;
수정 사항이 많아서 작업이 까다로웠을 것 같네요 😖

2024-09-23 04:59 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
> +    Optional<User> findUserByType(@Param("type") UserType type);
이 부분은 String으로 자동 mapping을 이용하는 건가요?

2024-09-23 05:02 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
> +    public ResponseEntity<CustomChecklistQuestionsResponse> readCustomChecklistQuestions(@UserPrincipal User user) {
어머 놓쳤네요! 수정했습니다~

2024-09-23 05:09 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/CookieResolverTest.java
> +        cookies[0] = new Cookie(CookieProvider.TOKEN_COOKIE_NAME, expectedToken);
굿~ 👍

2024-09-23 05:15 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthPrincipalArgumentResolver.java
> +        String token = cookieResolver.extractToken(request.getCookies());
extractToken() 메서드가 UserPrincipalArgumentResolver에서도 사용되고 있는데요, 이때는 위에서 null 체크를 하지 않아 해당 로직이 필요합니다! 그리고 내부에서 스트림을 돌리기 때문에 이전에 null 체크가 이루어져야 안전하게 메서드를 사용할 수 있다고 생각했습니다~

2024-09-23 05:16 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
> +                && Objects.equals(email, user.email) && type == user.type;
수정했습니다~!

2024-09-23 05:28 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/DBInitializer.java
> +    }
Guest 유저는 무조건 1명으로 유지되어야 할 것 같네요! 
Guest 유저가 존재하는지 확인하는 로직 추가하겠습니다~

2024-09-23 06:08 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +        return userRepository.getUserByType(UserType.GUEST);
UserType은 유니크값이 아니기 때문에 getBy를 호출할 때 2개 이상의 값이 있을 수도 있겠네요!
해당 메서드에 검증 로직 추가해주었습니다~

2024-09-23 06:29 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
> +    Optional<User> findUserByType(@Param("type") UserType type);
넵넵! 저장될 때 UserType 자체로 저장되기 때문에 가져올 때도 UserType으로 조회합니다.

2024-09-23 06:39 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/DefaultChecklistService.java
> +    }
static 변수를 사용해 한 번만 객체 생성이 이루어지도록 수정했습니다.

2024-09-23 06:56 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipal.java
> +public @interface UserPrincipal {
이름이 헷갈릴 수도 있겠네요! 현재로써는 이름을 적절히 바꿈으로써 해결하는 방법이 최선일듯한데요,
`AuthRequiredPrincipal`, `UserPrincipal`로 바꿔보았습니다. 괜찮은지 확인 한 번 해주세요~

2024-09-23 07:46 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/DBInitializer.java
> +    private final UserRepository userRepository;
좋습니다! 반영했어요~

2024-09-23 16:41 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/DefaultChecklistService.java
> +    private final ChecklistManageService checklistManageService;
시소 좋은 의견이네요~! 

많이 고민해봤으나 다음의 이유들로 코드를 분리하지 않았습니다.

- 디폴트 체크리스트와 질문들은 유저의 이해를 돕기 위해 만들어졌기 때문에 저희의 핵심 비즈니스 로직이 아닌, 언제든 없어지거나 변경될 수 있는 부분이라고 생각합니다.
- ChecklistManageService, QuestionManageService로 디폴트를 생성하는 코드가 분산되어 있으면 추후 작업할 때 디폴트로 만들기로 했던 것들이 어떤 것이 있었지? 라고 고민하게 되고, 그 코드를 찾고 이해하는데 시간이 걸릴 것 같습니다. 따라서 하나의 서비스에서 관리하는 것이 작업하기 편할 것으로 생각했습니다.

다른 의견 있으시면 편하게 이야기해주세요 😃

2024-09-24 01:09 UTC, shin-jisong approved these changes
수고하셨어요~!

2024-09-24 04:41 UTC, tkdgur0906 approved these changes

2024-09-24 04:41 UTC, tkdgur0906 commented
고생했습니다-

2024-09-24 06:07 UTC, tsulocalize approved these changes

2024-09-24 12:32 UTC, merged