[BE] 체크리스트 수정 API를 리팩토링한다.
woowacourse-teams/2024-bang-ggood pull request #631
Opened 2024-09-23 02:33 UTC by shin-jisong

## ❗ Issue
- #584 

## ✨ 구현한 기능
- 체크리스트 수정 API 리팩토링

## 📢 논의하고 싶은 내용

## 🎸 기타
작업 분량이 생각보다 많아서 오래 걸렸네요!
Service 위주로 봐 주세요

2024-09-23 14:37 UTC, JINU-CHANG requested changes
시소 수고하셨습니다 ~ 👍

2024-09-23 14:37 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> +        checklistService.updateChecklist(checklist, checklistRequest.toChecklistEntity(checklist.getRoom(), user));
ChecklistRequest 내부의 데이터로 Checklist 엔티티를 만드는 것이 아니라 외부에서 Room 엔티티를 받아와서 생성하는게 저는 조금 어색하게 느껴지는 것 같아요 🥲

2024-09-23 14:37 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> +    private void updateChecklistOptions(ChecklistRequest checklistRequest, Checklist checklist) {
파라미터로 받는 Checklist 네이밍이 `기존의 존재했던, 수정될 체크리스트`라는 의미를 좀 더 내포하고 있으면 좋겠어요!
의견정도이니 시소가 굳이 필요하지 않다고 생각되면 넘기셔도 됩니다~

2024-09-23 14:37 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> +                        .collect(Collectors.toList());
```suggestion
        List<ChecklistMaintenance> checklistMaintenances =
                checklistRequest.room().includedMaintenances().stream()
                        .map(maintenanceId -> new ChecklistMaintenance(checklist,
                                MaintenanceItem.fromId(maintenanceId)))
                        .toList();
```

2024-09-25 00:40 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
> +        IntStream.range(0, questions.size())
반영하였습니다!

2024-09-25 01:00 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> +        checklistService.updateChecklist(checklist, checklistRequest.toChecklistEntity(checklist.getRoom(), user));
대화 후 결정하였습니다!

2024-09-25 01:01 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> +    private void updateChecklistOptions(ChecklistRequest checklistRequest, Checklist checklist) {
해당 부분은 체크리스트가 수정될 상태는 아니고 **연결된 옵션이 수정될 상태**라고 생각하여
체크리스트와 분리하여 봐야 될 것 같다고 생각했습니다!

2024-09-25 01:03 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> +                        .collect(Collectors.toList());
반영하였습니다!

2024-09-25 01:04 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
> +    }
for문으로 수정하였습니다!

체크리스트 수정을 할 때는 질문은 수정이 불가하고 답변만 수정할 수 있기 때문에 질문들은 같아야 한다는 조건을 설정하였습니다 👍

2024-09-25 02:10 UTC, tkdgur0906 approved these changes

2024-09-25 06:48 UTC, merged