[BE] 체크리스트 삭제 API를 리팩토링한다.
woowacourse-teams/2024-bang-ggood pull request #640
Opened 2024-09-23 07:33 UTC by shin-jisong

## ❗ Issue
- #632 

## ✨ 구현한 기능
- 체크리스트 삭제 API 리팩토링

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-09-23 12:56 UTC, tkdgur0906 approved these changes
고생하셨습니다~~ 시소 짱

2024-09-23 12:56 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
> +
공백이요!

2024-09-23 12:56 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +
하는 김에 여기두!

2024-09-23 14:42 UTC, JINU-CHANG requested changes
코멘트할 게 별로 없네요! 수고하셨습니다 🚀

2024-09-25 01:22 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
> +
반영하였습니다!

2024-09-25 01:22 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
> +
반영하였습니다!

2024-09-25 01:23 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
> +    public void deleteChecklistById(User user, long id) {
반영했습니다!

2024-09-25 01:23 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +    }
반영했습니다!

2024-09-25 01:28 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
>      }
반영하였습니다!

2024-09-25 06:48 UTC, JINU-CHANG approved these changes

2024-09-25 08:20 UTC, merged