[FE] 지하철 노선을 업데이트하여 보여주고 roomInfonValidatedStore를 만들어 적용한다.
woowacourse-teams/2024-bang-ggood pull request #651
Opened 2024-09-24 08:52 UTC by ooherin

## ❗ Issue

- #587 
- #667

## ✨ 구현한 기능

### 1. 지하철 기능 업데이트

변경된 api 에 따라 가까운 지하철 노선을 2개 보여줄 수 있도록 수정했습니다.
또한 지하철 노선의 아이콘을 만들어 적용하였습니다. 

<img width="568" alt="스크린샷 2024-09-24 오후 5 37 35" src="https://github.com/user-attachments/assets/59a16fba-3aa0-4480-a087-c3924044a848">

### 2. checklistRoomInfoStore 에서 roomInfoNonInputStore 의 분리

기존에 roomInfo 에 들어있던 address, walkingTime을 지우고 새로운 `roomInfoNonInputStore` 을 만들어 넣어주었습니다.
해당 store 는 체크리스트 작성 form 에서 validation 이 필요한 인풋이 아닌 모든 요소들(주소, 지하철, 관리비, 방구조) 등을 관리하는 store 입니다. 

이를 관리하는 `useRoomInfoNonInput` 도 만들었습니다. 현재 지하철 노선 훅만 있는 상태이며 이후 관리비, 방구조 선택 함수도 추가될 예정입니다. 

### 3. FormField 의 ErrorMessage 컴포넌트 수정

해당 컴포넌트는 원래 에러 메세지만을 넣는 필드이나, 에러 메세지가 없는 상태에도 layoutshift 방지 및 gap 을 일정하게 유지하기 위해 에러 메세지 본연의 의미가 불확실해졌습니다. 따라서 네이밍을 `BottomMessageBox` 로 수정하였고, 모든 필드의 아래에 들어가게 하였습니다. 

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-09-24 11:26 UTC, healim01 requested changes
코멘트 달아놨습니다~ 확인해주세요

2024-09-24 11:26 UTC, healim01 commented on frontend/src/hooks/useRoomInfoNonInput.ts
흠.. 이름이 `useRoomInfoNonInput` 이다보니 인풋이 아닌 정확히 무슨 값인지 잘 직관적으로 다가오지 않는거 같아요..

2024-09-24 11:26 UTC, healim01 commented on frontend/src/store/roomInfoNonInputStore.ts
여기부터 다시 봐도 nonInput 이라는 네이밍은 정확히 뭘 스토어 하는지 잘 다가오지 않는 느낌이네요. 
그리고 현재 가지고 있는 스토어는 아예 주소 관련 로직만 있는거 같아서 차라리 `addressStore` 쪽으로 바꾸는건 어떠신가요?

2024-09-24 11:26 UTC, healim01 commented on frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
> +          nonInputAction.set('buildingName', data.buildingName);
`nonInput` 과 관련해서 아래에 코멘트 남겨놨습니다!

2024-09-24 11:26 UTC, healim01 commented on frontend/src/components/_common/FormField/FormField.tsx
> +  BottomMessageBox: ({ value, ...rest }: { value?: string } & HTMLAttributes<HTMLParagraphElement>) => (
`BottomMessgeBox` 로 바뀐 이유가 무엇일까요? 에러 메세지가 나타나는 칸이라 이전에 `ErrorMessage` 더 직관적인거 같습니다.

리안은 어떻게 생각하시나요?

2024-09-24 11:26 UTC, healim01 commented on frontend/src/components/_common/SubwayStation/NearSubwayStation.tsx
불필요한 코드가 추가된거 같네요

2024-09-24 11:26 UTC, healim01 commented on frontend/src/components/_common/SubwayStation/SubwayLineIcon/SubwayLineIcon.tsx
> +    background-color: ${({ color }) => (color ? color : 'black')};
`black` 도 가지고 있는 테마를 사용해주세요!

2024-09-24 11:26 UTC, healim01 commented on frontend/src/styles/reset.ts
> +
html 로 폰트 사이즈를 지정하신 이유가 있을까요? 
그리고 앞선 컨벤션으로`rem` 을 사용하기로 했고 글로벌 스타일에 기본 폰트 사이즈가 지정된 걸로 압니다! 

한번 확인해주세요!!

2024-09-24 20:34 UTC, skiende74 reviewed
수고하셨습니다~ UI예쁘네요.
코멘트 확인해주세요

2024-09-24 20:34 UTC, skiende74 commented on frontend/src/types/subway.ts
> +export type NearSubwayStations = SubwayStation[];
배열이냐아니냐의 차이만을 위해 별칭을 지어줄필요는 없을거같아요.

2024-09-24 20:34 UTC, skiende74 commented on frontend/src/components/_common/SubwayStation/SubwayLineIcon/SubwayLineIcon.tsx
> +  const isNumberSubwayName = lineName.slice(-2) === '호선' && !excludedSubwayNames.includes(lineName);
isNumber 보단 isNumeric이 문법상 맞을 거 같아요

2024-09-24 20:34 UTC, skiende74 commented on frontend/src/components/NewChecklist/NewRoomInfoForm/MaintenanceFee.tsx
> +      <FormField.BottomMessageBox value={errorMessage} />
제어컴포넌트에 undefined가 넘어가면 상태동기화 버그가 생겨서  ?? ''를 유지해주세요

2024-09-24 20:34 UTC, skiende74 commented on frontend/src/components/NewChecklist/NewRoomInfoForm/DepositAndRent.tsx
> +  const errorMessage = errorMessageDeposit || errorMessageRent;
제어컴포넌트에 undefined가 넘어가면 상태동기화 버그가 생겨서  || ''를 유지해주세요

2024-09-24 20:34 UTC, skiende74 commented on frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
> +  const { actions: nonInputAction } = useStore(roomInfoNonInputStore);
Action뒤에 s를 붙여주세요

2024-09-24 20:34 UTC, skiende74 commented on frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
> +  const errorMessage = errorMessageOccupancyMonth || errorMessageOccupancyPeriod;
제어컴포넌트에 undefined가 넘어가면 상태동기화 버그가 생겨서 ?? ''를 유지해주세요

2024-09-24 20:34 UTC, skiende74 commented on frontend/src/components/NewChecklist/NewRoomInfoForm/RoomContractTerm.tsx
> +      <FormField.BottomMessageBox value={errorMessage} />
나머지 모든곳에서도 ?? ''를 유지해주세요

2024-09-24 23:52 UTC, ooherin commented on frontend/src/hooks/useRoomInfoNonInput.ts
이 부분은 제이드랑 상의하고 리팩토링했던 건데, 헤일리가 그 때 없어서 설명을 못드렸네요... 이따 현장에서 상의해봅시다!

2024-09-24 23:53 UTC, ooherin commented on frontend/src/store/roomInfoNonInputStore.ts
위에 pr 내용에서도 말씀드렸다시피, input 이 아닌 모든 필드의 함수가 다 들어갈 예정입니다. store 랑 일관성을 맞추고자 저렇게 지었습니다. 사실 헤일리 의견도 많이 공감가는 내용이긴 해서 이따 말해보면 좋을 것 같습니다!

2024-09-24 23:57 UTC, ooherin commented on frontend/src/components/_common/SubwayStation/SubwayLineIcon/SubwayLineIcon.tsx
> +    background-color: ${({ color }) => (color ? color : 'black')};
아마 해당 색상은 없어질 것 같긴한데, 그렇게 하도록 하겠습니다!

2024-09-24 23:59 UTC, ooherin commented on frontend/src/styles/reset.ts
> +
앗 그렇군요! 사실 스토리북 설정을 하기 위해 설정을 한 것인데요. 스토리북에서는 헤일리가 html 설정을 한 global 스타일이 아닌 reset 스타일을 참조하고 있어, 해당 설정이 적용되지 않았었어요. 분명 html 에 rem 을 위한 설정을 해놓은 걸 찾고 싶었는데, 10px 이 아닌 62.5% 로 global 에 해놓으셨더라구요..! 

스토리북에서는 해당 속성이 적용이 안되서 고민을 해봐야 할 것 같습니다.

2024-09-25 00:01 UTC, ooherin commented on frontend/src/types/subway.ts
> +export type NearSubwayStations = SubwayStation[];
어느정도 공감합니다. 저 타입을 굳이 지정한 이유는 api에서 가져오는 타입이 저 타입이라서 굳이 타입을 지정해준것이긴 한데, returnType을 굳이 정의하지 않는 저희 컨벤션 상, 좀 불필요한 타입인것도 맞는 것 같습니다! 수정하도록 할게요

2024-09-25 00:05 UTC, ooherin commented on frontend/src/components/_common/SubwayStation/SubwayLineIcon/SubwayLineIcon.tsx
> +  const isNumberSubwayName = lineName.slice(-2) === '호선' && !excludedSubwayNames.includes(lineName);
네이밍에  의미를 정확하게 넣는 편이시군요! 
사실 정확히 말하면 '2호선'의 2는 string으로 숫자로 변환할 수 있는 numeric 이 정확한 것 같기는 하지만,
굳이 형변환의 의미가 필요하지 않은 경우에는 `isNumber` 도 나쁜 네이밍은 아니라고 생각합니다. 

저 함수의 가장 큰 목표는 해당 함수의 종류를 판별하는 것이고. 해당 호선이 '숫자로 형변환할 수 있는 호선인가?' 보다는 '숫자 호선인가?' 라고 생각하는 것이 더 직관적이라고 생각하기 때문입니다! 이따 더 얘기해보아요

2024-09-25 00:07 UTC, ooherin commented on frontend/src/components/_common/SubwayStation/NearSubwayStation.tsx
그렇네요 감사합니다!

2024-09-25 00:07 UTC, ooherin commented on frontend/src/components/_common/FormField/FormField.tsx
> +  BottomMessageBox: ({ value, ...rest }: { value?: string } & HTMLAttributes<HTMLParagraphElement>) => (
pr 내용 3번에 해당 내용이 있습니다!ㅎㅎ
더 자세히 설명드리자면, 에러 메제지가 뜨지 않는 Address 같은 필드에도 해당 컴포넌트가 들어가게 됩니다.
하지만, 이는 전혀 에러메세지를 표시할 용도가 아니고, 그저 다른 필드와의 gap 을 일정하게 유지시키기 위한 
UI 박스일 뿐입니다. 
따라서 해당 박스의 이름을 바꾼 것입니다.

2024-09-25 01:26 UTC, healim01 commented on frontend/src/styles/reset.ts
> +
```
    <Global
      styles={css`
        ${normalize}
        font-size: 10px;
      `}
    />
```

2024-09-25 02:03 UTC, skiende74 commented on frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
> +          roomInfoUnvalidatedStoreActions.set('address', data.address);
Store는 안붙여주셔도됩니다.

2024-09-25 02:06 UTC, healim01 commented on frontend/src/components/NewChecklist/NewRoomInfoForm/NearSubwayStations.tsx
> +  const { nearSubwayStation } = useStore(roomInfoUnvalidatedStore);
이 부분 컨벤션이 안지켜진거 같습니다 확인부탁드려요!

2024-09-25 02:06 UTC, healim01 commented on frontend/src/components/NewChecklist/NewRoomInfoForm/Address.tsx
> +      <FlexBox.Horizontal style={{ marginTop: '20px' }}>
20px -> 2rem

2024-09-25 02:07 UTC, healim01 commented on frontend/src/components/NewChecklist/SubmitModalWithSummary/SubmitModalWithSummary.tsx
> +  const actions = useStore(checklistRoomInfoStore, state => state.actions);
이부분도 actions 네이밍 변경부탁드려요~!

2024-09-25 02:08 UTC, healim01 commented on frontend/src/components/_common/SubwayStation/NearSubwayStationItem.tsx
> +const NearSubwayStationItem = ({ station }: { station: SubwayStation }) => {
props interface 는 외부로 선언하기로 해서 지켜주시면 좋을거 같아용~!

2024-09-25 02:09 UTC, healim01 commented on frontend/src/components/_common/SubwayStation/NearSubwayStationItem.tsx
> +      <FlexBox.Horizontal gap={'4px'}>
귀찮으시겠지만 px -> rem도 지켜주세영,,~~

2024-09-25 02:09 UTC, healim01 commented on frontend/src/components/_common/SubwayStation/SubwayLineIcon/SubwayLineIcon.tsx
> +const SubwayLineIcon = ({ lineName }: { lineName: SubwayLineName }) => {
여기 props 도요!

2024-09-25 02:23 UTC, ooherin commented on frontend/src/components/NewChecklist/NewRoomInfoForm/Address.tsx
> +      <FlexBox.Horizontal style={{ marginTop: '20px' }}>
이건 다음에 반영하겠습니다

2024-09-25 08:03 UTC, ooherin commented on frontend/src/components/NewChecklist/SubmitModalWithSummary/SubmitModalWithSummary.tsx
> +  const actions = useStore(checklistRoomInfoStore, state => state.actions);
다음 pr 에서 수정하겠습니다

2024-09-25 08:08 UTC, skiende74 approved these changes

2024-09-25 08:08 UTC, merged