[BE] 리프레시 토큰 기능을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #654
Opened 2024-09-24 16:17 UTC by JINU-CHANG

## ❗ Issue

- #627 

## ✨ 구현한 기능

- 로그인시 리프레시 토큰 쿠키에 담아 전달하는 기능 구현
- 리프레시토큰 재발급하는 API 구현
- 토큰 생성시 타입 넣어서 생성하도록 변경

## 📢 논의하고 싶은 내용

## 🎸 기타

- 작업 분량이 많아 꼼꼼하게 확인해주세요!

2024-09-25 15:58 UTC, tkdgur0906 requested changes
전체적으로 잘 작성해주셔서 딱히 코멘트가 없네요!
간단한 것만 남겼으니 확인해주세요!

2024-09-25 15:58 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
> +    @PostMapping("/accessToken/reIssue")
reissue가 한단어 아닌가용?

2024-09-25 15:58 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieResolver.java
>          if (cookies == null) {
지금 생각난건데 쿠키 length가 0인 경우도 예외처리해도 좋을 것 같아요!

2024-09-26 01:10 UTC, shin-jisong approved these changes
간단한 사항만 있어서 바로 approve 하겠습니다!

2024-09-26 01:10 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/JwtTokenProviderFixture.java
> +        return new JwtTokenProperties(1800000L, 1800000L); // 30분
이건 상수로 추출하는 거 어떨까요?

2024-09-26 01:57 UTC, tsulocalize approved these changes
고생 많으셨습니다!

2024-09-26 05:15 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieResolver.java
>          if (cookies == null) {
반영했습니다!

2024-09-26 05:16 UTC, tkdgur0906 approved these changes

2024-09-26 05:17 UTC, merged

2024-09-26 05:17 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/JwtTokenProviderFixture.java
> +        return new JwtTokenProperties(1800000L, 1800000L); // 30분
반영했습니다~