[BE] Redierect URI를 여러 개 받을 수 있도록 카카오 로그인 구현 방식을 변경한다.
woowacourse-teams/2024-bang-ggood pull request #725
Opened 2024-10-03 08:37 UTC by JINU-CHANG

## ❗ Issue

- #724 

## ✨ 구현한 기능

- OauthLoginRequest클래스내에 redirectUris 필드 추가
- OauthRequestProperties 클래스 생성
  - redirect uri를 매칭하는 코드가 추가되면서 OauthClient 내부 코드가 길어져 OauthRequestProperties 클래스로 책임 분리
- OauthRequestProperties 테스트코드 추가

## 📢 논의하고 싶은 내용

## 🎸 기타

로그인 가능 페이지가 여러곳이 되면서 rediect uri을 2개 이상 사용하게 되었고, 기존에 1개만 받을 수 있던 형태에서 여러 개를 받을 수 있도록 구현 방식을 변경했습니다.

2024-10-03 09:16 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
> +    }
redirectUri이 List 형태로 저장되어야 하는데, @Value 어노테이션으로는 yml파일의 리스트 값을 바로 가져오지 못하더라구요.
이에 대한 대안으로`@ConfigurationProperties(prefix = "kakao")` 어노테이션을 붙이는 방법이 있으나 아래와 같이 getter/setter를 모두 설정해주어야 한다는 점 때문에 사용하지 않았습니다. 지금의 방식이 최선이었는데, 더 좋은 방법있으면 알려주세요!

```java
// Getters and Setters
    public String getTokenPostUri() {
        return tokenPostUri;
    }

    public void setTokenPostUri(String tokenPostUri) {
        this.tokenPostUri = tokenPostUri;
    }

    public String getUserInfoRequestUri() {
        return userInfoRequestUri;
    }

    public void setUserInfoRequestUri(String userInfoRequestUri) {
        this.userInfoRequestUri = userInfoRequestUri;
    }

    public String getGrantType() {
        return grantType;
    }

...
```

2024-10-03 10:08 UTC, tsulocalize approved these changes
특별히 리뷰할만한 내용은 없는 것 같네요
오타만 고쳐주세요~

2024-10-03 10:08 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
> +    }
저는 지금 방식도 괜찮은 것 같아요!

2024-10-04 01:05 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
> +    }
함수명으로 내용이 잘 전달되는 것 같아 이렇게 가도 될 것 같습니다!

2024-10-04 01:06 UTC, shin-jisong approved these changes
수고하셨습니다~

2024-10-04 01:29 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
> +    }
결국에 롬복을 도입할거면 setter/getter로 해두구 롬복 적용할때 달아줘도 좋을 것 같아요!

2024-10-04 01:59 UTC, tkdgur0906 requested changes
고생하셨습니다!
다른 리뷰 반영되면 제가 머지할게요!

2024-10-04 06:26 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/OauthFixture.java
> +    public static final String INVALID_REGISTERD_REDIRECT_URI = "localhost:8081";
찾아서 모두 고쳐줬어요~

2024-10-04 06:33 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
> +    }
setter/getter 결국 지워야할 코드일 것 같아서 롬복 도입하면서 그때 수정하도록 할게요!

2024-10-04 06:50 UTC, tkdgur0906 approved these changes

2024-10-04 06:50 UTC, merged