[BE] 좋아요 중복 요청 시 정상 상태코드 반환 및 중복 저장을 방지한다.
woowacourse-teams/2024-bang-ggood pull request #739
Opened 2024-10-04 08:25 UTC by tkdgur0906

## ❗ Issue

- #737 

## ✨ 구현한 기능
- 좋아요 중복 저장 방지
- 좋아요 요청 시 항상 204 반환

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-10-05 00:44 UTC, tsulocalize requested changes
수고하십니다!

2024-10-05 00:44 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
> +        return checklistLikeRepository.existsByChecklist(checklist);
existsByChecklist 메서드에 동시성 제어는 되어 있나요?
쿼리로 짜여있다면 `For Update`, JPA query로 되어 있다면 `@Lock`이 필요할 것 같네요

2024-10-05 09:36 UTC, shin-jisong approved these changes
수고하셨습니다!

2024-10-06 04:18 UTC, JINU-CHANG approved these changes
Approve하면서 사소한 코멘트 하나 남겼습니다~ 수고하셨어요!

2024-10-06 04:18 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/like/controller/ChecklistLikeE2ETest.java
> +                .statusCode(204);
여기 포함해서 다른 곳도 DisplayName도 함께 바뀌면 좋을 것 같아요!

2024-10-15 06:53 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
> +        return checklistLikeRepository.existsByChecklist(checklist);
락은 현재 pr에서 반영하지 않고 새로운 pr에서 반영해보겠습니다!

2024-10-15 06:53 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/like/controller/ChecklistLikeE2ETest.java
> +                .statusCode(204);
변경했습니다~

2024-10-16 01:34 UTC, tsulocalize approved these changes

2024-10-16 01:34 UTC, merged