[BE] 토큰 확인하는 API를 구현한다.
woowacourse-teams/2024-bang-ggood pull request #767
Opened 2024-10-07 13:23 UTC by JINU-CHANG

## ❗ Issue

- #766 

## ✨ 구현한 기능

- 리프레시 토큰의 존재 여부를 반환하는 `/refreshToken/check` API 구현
- 테스트 코드 추가
- 이전 PR에서 테스트 깨지는 부분 수정

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-10-08 00:41 UTC, shin-jisong requested changes
수고하셨습니다! 간단한 사항만 남겼는데 머지 될까 봐 RC로 남겨요 :ㅋㅋ:

2024-10-08 00:41 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/RefreshTokenCheckResponse.java
> +    public static RefreshTokenCheckResponse from (boolean isRefreshTokenExist) {
여기 from 뒤에 공백이 잘못 들어간 것 같아요!

2024-10-08 00:41 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/repository/ChecklistStationRepository.java
> +    List<ChecklistStation> findByChecklist(@Param("checklist") Checklist checklist);
저희 id로 빼기로 했던 것 같아요!
일괄적으로 수정하는 일정이 있으면 따로 수정하지는 않아도 될 것 같지만 수정한 파트이길래 리뷰 남깁니다 👀

2024-10-08 01:08 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
> +    @GetMapping("/refreshToken/check")
뒤늦게 발견했는데 API URL에서는 kebab-case 사용해야 될 것 같아요!

2024-10-08 01:54 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/RefreshTokenCheckResponse.java
> +    public static RefreshTokenCheckResponse from (boolean isRefreshTokenExist) {
반영했습니다!

2024-10-08 02:01 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
> +    @GetMapping("/refreshToken/check")
🍗

2024-10-09 14:14 UTC, tkdgur0906 approved these changes
고생하셨습니다~

2024-10-09 14:14 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> +        assertThatCode(() -> authService.reissueAccessToken(tokenResponse.refreshToken()))
이 pr에서 AuthServiceTest에 문장형으로 작성된 DisplayName 수정해도 편할 것 같아요~

2024-10-10 01:08 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/station/repository/ChecklistStationRepository.java
> +    List<ChecklistStation> findByChecklist(@Param("checklist") Checklist checklist);
테스트가 깨져서 추가한 부분이여서 제가 바꾸는 것보다 나중에 함께 수정하면 좋을 것 같아요~

2024-10-10 01:08 UTC, tsulocalize approved these changes
고진감래 하셨습니다!

2024-10-10 01:48 UTC, shin-jisong approved these changes
머지하겠습니다~

2024-10-10 01:48 UTC, merged