[BE] 회원가입 기능을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #774
Opened 2024-10-09 08:46 UTC by tkdgur0906

## ❗ Issue

- #729 

## ✨ 구현한 기능
- 이메일, 비밀번호 클래스 분리
- 비밀번호 암호화
- 회원가입

## 📢 논의하고 싶은 내용
### 비밀번호 암호화 시 필요한 Salt 생성 방법
현재 비밀번호 암호화 시 Salt가 필요한데, 사용자마다 고유한 값이 필요해 이메일을 사용해 생성하고 있습니다.
그래서 PasswordEncoder의 encode() 호출시 email, password를 넘겨야합니다.
하지만 비밀번호 정책을 검증하는 책임이 Password 클래스에 있다보니, 순수한 비밀번호 값을 생성자에 넘겨야합니다.
그래서 Password 클래스가 PasswordEncoder를 필드로 가지고 있게 되는데, 암호화 시 이메일이 필요해서 Password 생성자에 email을 같이 넘겨야 되는 상황입니다.
```
public Password(String email, String value) {
        validatePassword(value);
        this.value = passwordEncoder.encode(email, value);
    }
```
개선 가능 방안은 다음과 같습니다.
- Salt를 email을 통해 생성하는 것이 아닌 랜덤 생성으로 바꾼다.
- 랜덤 생성 객체는 PasswordEncoder 내부 필드로 가지고 있을 것 같습니다.

추가적인 다른 의견 있으시면 논의하면 좋을 것 같습니다.

---

### 비밀번호 암호화 시 필요한 Salt 저장 방법
만약 이메일 대신 랜덤하고 유저마다 고유한 값으로 Salt를 생성한다면 저장할 방법이 필요합니다.
세가지 방안을 생각했습니다.
1. password와 같이 저장
- db에 비밀번호가 `vI8aWBnW3fID.ZQ4/zo1G.q1lRps.9cGLcZEiGDMVr5yUP1KUOYTa` 같이 저장됐을 시  처음 22개 문자는 salt값, 나머지는 암호화된 비밀번호입니다.
- salt값은 16바이트 값으로 디코딩하여 다시 사용하는 방식입니다.
- 해당 방식이 Spring Security에서 Salt를 관리하는 방식이라고 합니다.
2. User 테이블 컬럼으로 Salt 추가
3. Salt 테이블 따로 생성해 저장

Salt 생성 시 email을 사용하지 않도록 바뀐다면 고민해봐야할 것 같습니다.

---

### 회원가입 동시성 처리
현재 코드에서 회원 가입시 같은 이메일로 요청이 동시에 온다면 둘다 회원가입 되는 문제가 발생할 수 있습니다.
```
@Transactional
    public Long register(RegisterRequestV1 request) {
        if (userRepository.existsByEmailAndUserType(new Email(request.email()), LoginType.LOCAL)) {
            throw new BangggoodException(ExceptionCode.USER_EMAIL_ALREADY_USED);
        }

        return userRepository.save(request.toUserEntity()).getId();
    }
```
User 테이블의 email과 LoginType을 같이 unique 제약조건을 설정하면 해당 문제를 해결할 수 있습니다.
만약 제약 조건 추가시 코드는 다음과 같이 작성할 수 있을 것 같습니다.

```
@Transactional
public void register(RegisterRequestV1 request) {
    try {
        userRepository.save(request.toUserEntity()).getId();
    } catch (DataIntegrityViolationException e) {
        // 유니크 제약 조건 위반 시 처리
        throw new BangggoodException(ExceptionCode.USER_EMAIL_ALREADY_USED);
    }
}
```
현재 테이블에 유니크 제약조건이 안걸려 있기 때문에 제약조건 거는 것에 대해 의견 부탁드립니다.

## 🎸 기타

2024-10-10 01:24 UTC, shin-jisong requested changes
수고하셨습니다 카피! (본문 수정 중)

2024-10-10 01:24 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
> +    @PostMapping("/v1/register")
oauth와 구분되는 path를 사용하는 것이 좋을 것 같은데 `/v1/local-auth/register` 어떨까요?
혹은 다른 적절한 path가 있다면 좋을 것 같네요!

2024-10-10 01:24 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/Password.java
> +            Pattern.compile("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{6,}$");
사용한 PASSWORD 패턴 전략도 본문에 적어 주시면 좋을 거서 같아요!

2024-10-10 01:24 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
> +    boolean existsByEmailAndUserType(Email email, LoginType loginType);
저희 쿼리문에서는 JPA 사용하지 않고 실제 쿼리를 작성하기로 했어서 value값으로 조회해야 될 것 같아요!

2024-10-10 01:24 UTC, shin-jisong commented on backend/bang-ggood/src/main/resources/data.sql
> +VALUES ('방방이', 'bang-ggood@gmail.com', 'password1234', 'USER', 'LOCAL', '2024-07-22 07:56:42', '2024-07-22 07:56:42', false);
이거 VALUE 넣을 때 암호화된 값으로 넣어야 될 것 같아요!

2024-10-10 01:24 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> +        assertThat(findUser.getPassword().getValue()).isNotEqualTo(password);
서비스 테스트니까 암호화한 결과값이랑 같은지 보는 게 좋을 것 같아요!

2024-10-10 01:24 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/user/domain/EmailTest.java
> +class EmailTest {
테스트를 꼼꼽하게 해 주셨네요 👍

2024-10-10 01:27 UTC, tsulocalize commented
1. 랜덤에 한표 드립니다. 랜덤도 요소를 여러가지 섞으면 pseudo-random으로 보이게 할 수 있을 겁니다.
2. password와 함께 저장 한표. 필요한 곳에 데이터가 있어야 된다고 생각하기 때문
3. 유니크 거시죵

2024-10-10 02:32 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
> +    boolean existsByEmailAndUserType(Email email, LoginType loginType);
확인해 봤는데 그렇게 작성하려면 nativeQuery 옵션을 켜야 되더라고요!
ENUM에 대해서는 따로 값을 꺼낼 필요는 없을 것 같아요~
실제 쿼리는 Id 같은 부분에 대해서만 적용하면 될 것 같습니다

2024-10-10 04:29 UTC, JINU-CHANG requested changes
카피 전체적으로 잘 구현해주셨네요 👍

1. 랜덤으로 Salt 생성하는게 안전할 것 같아요.
2. 하나의 암호화된 문자열이라는 생각이 들어 굳이 따로 테이블을 빼지 않고 password와 같이 저장하는게 좋을 것 같아요.
3. 안 그래도 필요했는데 유니크 제약조건 좋습니다!

2024-10-10 10:40 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
> +    @PostMapping("/v1/register")
반영했습니다!

2024-10-10 11:20 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> +        assertThat(findUser.getPassword().getValue()).isNotEqualTo(password);
내부에서 salt를 생성하기 때문에 암호화한 결과값을 동일하게 생성하는게 마땅치 않은 것 같네요
PasswordEncoder의 메서드 시그니처를 바꾸지 않는 이상 테스트 하기가 어려워 현재로써는 방법이 떠오르지 않아서 일단 유지했습니다!

2024-10-10 11:37 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordEncoder.java
> +            throw new RuntimeException(e);
해시 에러로 바꿔서 던졌습니다!

2024-10-10 11:40 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/Password.java
> +    private static final PasswordEncoder passwordEncoder = new PasswordEncoder();
static 메서드로 만들라는 것인가요??

2024-10-10 11:41 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
> +    boolean existsByEmailAndUserType(Email email, LoginType loginType);
(Email email, LoginType loginType)  대신에 (String email, LoginType loginType)로 받으라는 것인가요??

2024-10-11 01:03 UTC, shin-jisong requested changes

2024-10-11 01:03 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordEncoder.java
> +    public String encode(String password) {
카피! 해당 부분 잘 바꿔주셨는데 추후 재사용성을 고려하여 encode 로직에서 salt를 받아야 될 것 같은데 어떻게 생각하시나요? 🤔

2024-10-11 01:33 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> +        assertThat(findUser.getPassword().getValue()).isNotEqualTo(password);
Salt를 주입받는 식으로 변경해서 값이 같은지에 대한 테스트로 변경했습니다!!!

2024-10-11 01:34 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordEncoder.java
> +    public String encode(String password) {
좋은 방법인 것 같아요! 
encode를 외부에서 salt를 받도록 변경했습니다!

2024-10-11 01:36 UTC, shin-jisong approved these changes
수고하셨습니다~~!!

2024-10-11 03:11 UTC, tsulocalize approved these changes
沐雨櫛風(목우즐풍)하셨습니다!

2024-10-11 03:11 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/Password.java
> +        this.value = passwordEncoder.encode(value, passwordEncoder.getSalt());
1. static으로 만들어도 무방할 것 같은데, 추후에 bean이 필요한 상황을 생각하고 있다면 반영하지 않으셔도 됩니다.
2. encode(String value) 메서드도 있으면 사용하기 편할 것 같아요~

2024-10-11 03:11 UTC, tsulocalize commented on backend/bang-ggood/src/main/resources/schema.sql
> +    CONSTRAINT unique_email_login_type UNIQUE (email, login_type)
prod 환경에 배포할 때 데이터 정합성 일치하도록 주의해주세요!

2024-10-11 04:34 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/Password.java
> +        this.value = passwordEncoder.encode(value, passwordEncoder.getSalt());
1. 빈에 대한 판단은 로그인 PR에서 반영하는 게 좋을 것 같아 그때 생각해보겠습니다!
2. encodeWithGeneralSalt(String password) 메서드를 만들어서 따로 처리했습니다!

2024-10-11 05:18 UTC, JINU-CHANG approved these changes

2024-10-11 05:19 UTC, merged