[BE] 일반 로그인을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #775
Opened 2024-10-10 04:06 UTC by shin-jisong

## ❗ Issue
- #755 

## ✨ 구현한 기능
- 일반 로그인 구현

## 📢 논의하고 싶은 내용
- #774에서 반영되는 내용에 따라 코드 수정이 많을 듯합니다!
먼저 머지되고 관련 내용 합쳐야 될 것 같습니다 🥲

## 🎸 기타

2024-10-11 00:10 UTC, JINU-CHANG requested changes
시소 고생많으셨습니다 👍 
전반적으로 잘 작성해주셔서 사소한 코멘트 몇가지만 남겨보았어요!

2024-10-11 00:10 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private void checkPassword(LocalLoginRequestV1 request, User user) {
```suggestion
    private void validatePassword(LocalLoginRequestV1 request, User user) {
```
지금까지는 검증 메서드를 validate라고 했던 것 같아서 제안드려봅니다~!

2024-10-11 00:10 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private static void validateTokenOwnership(User user, AuthUser accessAuthUser, AuthUser refreshAuthUser) {
위로 올라온 이유가 있나요??

2024-10-11 00:10 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> +    @DisplayName("카카오 로그인 성공 : 회원 가입시 디폴트 체크리스트를 추가한다.")
컨벤션이 명사구 형태여서 저번 PR에서 수정했던 기억이 있는데 다시 문장형으로 수정하신 이유가 있나요?-?

2024-10-11 03:02 UTC, tkdgur0906 requested changes
고생많으셨습니다!
충돌 해결된 후에 한번더 볼게요!

2024-10-11 08:34 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private void checkPassword(LocalLoginRequestV1 request, User user) {
해당 부분은 정책에 따라 규칙에 맞는가 확인하는 것이 아닌 맞는가 체크하는 부분이라 생각해서 validate 명명보다는 비즈니스 로직 명명을 가질 수 있도록 구현하였습니다!

2024-10-11 08:35 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private static void validateTokenOwnership(User user, AuthUser accessAuthUser, AuthUser refreshAuthUser) {
머지하다가 그렇게 됐네요.... 다시 내려두었습니다 🔽

2024-10-11 08:35 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> +    @DisplayName("카카오 로그인 성공 : 회원 가입시 디폴트 체크리스트를 추가한다.")
이것도 머지하다가... 충돌 해결한다고... 🥲
수정해 두었습니다!

2024-10-11 08:36 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
> +        return !Objects.equals(this.password, password);
로직이 바뀌었습니다!

2024-10-12 16:17 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordEncoder.java
> +        if (parts.length != 2) {
`PASSWORD_AND_SALT_LENGTH`로 상수화하였습니다!

2024-10-12 16:20 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/Password.java
> +            return;
각 입력값을 그대로 넣어 주는 것이 좋을 것 같아서 해당 로직으로 작성했습니다
다만 isEmpty에 해당할 경우가 빈 문자열인 "" 에 해당할 것 같은데 null을 넣는 것이 더욱 명확한 코드 전달일 것 같아 null을 넣는 것으로 대체하였습니다!

2024-10-13 07:54 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private void checkPassword(LocalLoginRequestV1 request, User user) {
제가 이해한 바에 따르면, 단순히 비밀번호가 다른지 체크하는 부분은 정책적인 부분이 아니라 네이밍을 다르게 가져가고 싶다는 의미로 이해했어요! 하지만 null, empty 체크도 비슷한 경우라고 생각되는데 validate 메서드명을 사용했던 것 같아서 이 부분은 어떻게 생각하는지 궁금합니다 ~

2024-10-13 14:26 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private void checkPassword(LocalLoginRequestV1 request, User user) {
null 혹은 empty 체크는 값 자체의 형식에 대한 검증이라 생각해요!
validate 검증 로직은 주로 입력 데이터가 특정 형식, 패턴 또는 규칙에 부합하는지 확인하는 데 사용하는 명명이라는 생각입니다
반면에 비밀번호 일치 여부를 확인하는 로직은 단순히 입력 데이터의 형식 검증이 아닌, 기존 데이터와 비교하여 중요한 비즈니스 결정을 내리는 과정이라 생각했어요!
validate라는 검증의 의미만 담기에는 다소 의미가 축소되는 느낌이 있다고 판단하였습니다

2024-10-14 03:50 UTC, tkdgur0906 approved these changes
짱짱 고생많으셨습니다~

2024-10-14 03:56 UTC, JINU-CHANG approved these changes

2024-10-14 04:15 UTC, tsulocalize reviewed
수고하셨어요~
간단한 코멘트만 확인하고 바로 approve 할게요!

2024-10-14 04:15 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/Password.java
> +            return;
Password라는 도메인이 null 허용이라는 게 null로 로그인 가능하다? 는 느낌이 들었어요.
개인적인 의견이지만 exception을 던지면 좋을 것 같아요!

2024-10-14 07:03 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/Password.java
> +            return;
반영하였습니다~!

2024-10-15 01:02 UTC, tsulocalize approved these changes

2024-10-15 01:02 UTC, merged