[BE] 방끗 자체 에러코드를 구현한다.
woowacourse-teams/2024-bang-ggood pull request #789
Opened 2024-10-12 16:59 UTC by shin-jisong

## ❗ Issue
- #788 

## ✨ 구현한 기능

## 📢 논의하고 싶은 내용

## 🎸 기타
저희가 만든 방끗 자체 에러코드와 기존의 ExceptionCode가 잘 맵핑되어 있는지 노션을 비교해가며 확인해 주세요!
재차 검증을 거쳤으나 워낙 방대해서 여러 사람의 교차 검증이 필요합니다 👍

방끗 자체 에러코드를 `BangggoodCode`로 명명하였는데 더 좋은 네이밍 있으면 추천 바랍니다

2024-10-13 08:10 UTC, JINU-CHANG approved these changes
시소~ 작업하면서 정신없었을텐데 너무 고생하셨습니다 👍

2024-10-13 08:10 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
> +    OAUTH_REDIRECT_URI_MISMATCH(HttpStatus.BAD_REQUEST, BangggoodCode.AUTH_TOKEN_INVALID, "일치하는 Redirect URI가 존재하지 않습니다."),
```suggestion
    OAUTH_REDIRECT_URI_MISMATCH(HttpStatus.BAD_REQUEST, BangggoodCode.OAUTH_SERVER_ERROR, "일치하는 Redirect URI가 존재하지 않습니다."),
```

![image](https://github.com/user-attachments/assets/251059da-c422-4cad-a8ea-0b3fb008273b)

2024-10-13 08:10 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
> +    QUESTION_HIGHLIGHT_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, BangggoodCode.QUESTION_ERROR, "잘못된 하이라이트 키워드가 존재해 질문을 생성할 수 없습니다."),
```suggestion
    QUESTION_HIGHLIGHT_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, BangggoodCode.CHECKLIST_SERVER_ERROR, "잘못된 하이라이트 키워드가 존재해 질문을 생성할 수 없습니다."),
```
![image](https://github.com/user-attachments/assets/1c7037b8-1fdc-461b-a4bc-fceefa1a7fe0)

2024-10-13 08:10 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
> +    CHECKLIST_NOT_OWNED_BY_USER(HttpStatus.BAD_REQUEST, BangggoodCode.CHECKLIST_ERROR, "유저의 체크리스트가 아닙니다."),
```suggestion
    CHECKLIST_NOT_OWNED_BY_USER(HttpStatus.BAD_REQUEST, BangggoodCode.UNAUTH_ERROR, "유저의 체크리스트가 아닙니다."),
```
![image](https://github.com/user-attachments/assets/67dca854-fee9-489d-a27e-23d3372e3bff)

2024-10-13 08:10 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/BangggoodCode.java
> +public enum BangggoodCode {
- CommonExceptionCode
- ClientExceptionCode

1) 프/백이 공통으로 사용한다, 2) 예외 코드 이렇게 2가지 뜻이 드러나있으면 좋겠어요!
제안드려봅니다 🙇‍♀️

2024-10-13 14:33 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/BangggoodCode.java
> +public enum BangggoodCode {
BangggoodException의 하위개념으로 BangggoodCode 명명을 사용해 보았는데
BangggoodExceptionCode의 명명은 너무 긴 것 같아 해당 명명으로 끝내기는 하였습니다!
다른 분들도 의견 달아 주시면 그걸로 반영해 볼게요~~

2024-10-14 04:39 UTC, tkdgur0906 requested changes
하나하나 잘 수정해주셨네요!
의견남겼으니 확인부탁드립니다~

2024-10-14 04:39 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/BangggoodCode.java
> +}
AUTH_TOKEN_NOT_OWNED_BY_USER,
AUTH_TOKEN_USER_MISMATCH,
GUEST_USER_NOT_FOUND,
GUEST_USER_UNEXPECTED_EXIST,
LIKE_ALREADY_EXISTS,
LIKE_NOT_EXISTS,
이 6개는 노션에 X 표시 되어있는데 여기서는 표기하는 것인가요?

2024-10-14 04:39 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/BangggoodCode.java
> +public enum BangggoodCode {
Client가 이름에 들어가있으면 좋을 것 같아요!

2024-10-14 04:39 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
> +    CHECKLIST_NOT_OWNED_BY_USER(HttpStatus.BAD_REQUEST, BangggoodCode.CHECKLIST_ERROR, "유저의 체크리스트가 아닙니다."),
노션에 BAD_REQUEST 대신 UNAUTHROIZED로 바뀌어있어요!

2024-10-14 06:49 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/BangggoodCode.java
> +}
해당 부분을 이야기하며 사라질 코드라서 X 표시를 해 두었던 걸로 기억해요!
현재로서는 지우면 로직상 에러가 나서 임의로 `BangggoodCode`에 동일한 이름을 맵핑해 두었습니다
머지하면서 지우면 될 것 같네요 🤔

2024-10-14 06:49 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/BangggoodCode.java
> +public enum BangggoodCode {
`ClientExceptionCode`로 변경하였습니다!

2024-10-15 01:28 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/BangggoodException.java
> +    }
메서드명이 명확하면 좋겠습니다!

2024-10-15 01:35 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/BangggoodException.java
> +    }
반영하였습니다!

2024-10-15 01:38 UTC, tsulocalize approved these changes

2024-10-15 04:41 UTC, tkdgur0906 approved these changes

2024-10-15 04:41 UTC, merged