체크리스트 질문 조회 API를 구현한다.
woowacourse-teams/2024-bang-ggood pull request #83
Opened 2024-07-24 10:00 UTC by shin-jisong

## ❗ Issue

- #76

## ✨ 구현한 기능
- 체크리스트 질문 조회 기능을 구현한다.

## 📢 논의하고 싶은 내용
-  category_priority 스키마에서 category_id를 TINYINT 대신 INTEGER를 적용해야 정상적으로 작동된다.
기존 설계에서는 TINYINT를 적용하기로 하였으나 클래스 설정을 INTEGER로 하여 해당 문제가 발생함.
논의 후 변경 예정이다.

## 🎸 기타

2024-07-24 10:18 UTC, tsulocalize requested changes

2024-07-24 10:18 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Questionlist.java
> +    }
getQuestion으로 가져와서 q.getSubtitle() / q.getTitle()을 쓰는 건 어떻게 생각하시나요?

2024-07-24 10:18 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
> +    }
return type을 List로 주는 건 어떨까요?

2024-07-24 10:19 UTC, JINU-CHANG reviewed
간단히 코멘트 남겼습니다! 
readChecklistQuestion메서드는 시간남을 때 조금 더 리팩토링해보면 좋을 것 같아요 😃

2024-07-24 10:19 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
> +    private final List<Integer> questionIds;
중복제거할 수 있는 Set 자료구조가 더 적합해보여요

2024-07-25 01:20 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Questionlist.java
> +    }
현재 구조에서는 이 방식이 더 합리적인 것 같아 채택하였는데 추후 재활용성이 떨어지면 리팩토링하는 방식으로 가 보겠습니다!

2024-07-25 01:33 UTC, shin-jisong commented
모두 반영 완료하였습니다~

2024-07-25 01:58 UTC, tsulocalize approved these changes

2024-07-25 02:02 UTC, JINU-CHANG approved these changes

2024-07-25 02:03 UTC, merged