[BE] 비밀번호 재설정 기능을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #843
Opened 2024-10-21 04:03 UTC by tkdgur0906

## ❗ Issue

- #807 

## ✨ 구현한 기능

- 이메일로 인증번호 전송
- 인증번호 검증
- 재설정된 비밀번호로 업데이트

## 📢 논의하고 싶은 내용

## 🎸 기타
LocalDateTime 테스트를 위해 Clock을  빈으로 등록했습니다.
yml파일 mail관련 설정 업데이트 예저입니다.

2024-10-21 06:06 UTC, shin-jisong requested changes
수고하셨습니다~

2024-10-21 06:06 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private static final int PASSWORD_RESET_CODE_EXPIRED_MINUTES = 3;
5분 혹은 10분이 적당하지 않을까요?!

2024-10-21 06:06 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +                new Email(request.email()), new Password(request.newPassword()));
여기서 패스워드 리셋 코드 저장한 걸 삭제하는 건 어떨까요?!

2024-10-21 06:06 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
> +
로그인 타입도 지정해 줘야 될 것 같아요!

2024-10-21 06:06 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/repository/PasswordResetCodeRepositoryTest.java
> +    @DisplayName("특정 시간보다 나중에 생성된 비밀번호 초기화 코드 존재 시 참 반환")
컨벤션이랑 살짝 다른 것 같아서 확인해 주세요!

2024-10-21 06:45 UTC, tsulocalize reviewed
간단한 리뷰 남겨드렸습니다~

2024-10-21 06:45 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
> +    @DisplayName("비밀번호 재설정 선공")
선공 -> 성공

2024-10-21 06:45 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/MailSenderTest.java
> +    @DisplayName("이메일 전송 시 send 메소드 호출")
+ 성공

2024-10-24 15:53 UTC, JINU-CHANG requested changes
수고많으셨어요~! 코멘트 몇가지 남겼습니다 🚀

2024-11-11 02:31 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private static final int PASSWORD_RESET_CODE_EXPIRED_MINUTES = 3;
5분으로 변경했습니다!

2024-11-11 02:46 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +                new Email(request.email()), new Password(request.newPassword()));
반영했습니다!

2024-11-11 02:48 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
> +
오 완전 예리한 리뷰네요, 수정했습니다!

2024-11-11 03:28 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/domain/PasswordResetCode.java
> +public class PasswordResetCode extends BaseEntity {
일단 어딘가에 저장되어야하긴 해서 DB에 저장했습니다.
유효시간도 있다보니 레디스에 저장하는게 최선 같은데, 우선은 간단하게 DB에 저장하는 방식으로 구현했습니다!

2024-11-11 03:35 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
> +    @PostMapping("/v1/password-reset/new-password")
반영했습니다!

2024-11-11 03:38 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    public void sendPasswordResetEmail(ForgotPasswordRequest request) {
메서드가 메일 보내는 api랑 같이 묶여있어서 붙이지 않았습니다!
save만 단건으로 트랜잭션 처리되도 괜찮을 것 같아요

2024-11-11 03:58 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/ConfirmPasswordResetCodeRequest.java
> +}
Dto에서 email 검증하도록 변경했습니다!

2024-11-11 04:08 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
> +    private final Clock clock;
비밀번호 찾기에 대한 서비스를 만들어서 분리했습니다!

2024-11-11 05:48 UTC, tsulocalize requested changes
코멘트 추가해두었습니다~

2024-11-11 05:48 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordResetService.java
> +    }
코드를 확인한 뒤에 `확인했다`라는 정보를 어디에 기록해두고 있나요?
현재 상태로는 코드 확인 절차 없이도 비밀번호 리셋이 가능한 것 같아 보이네요

2024-11-11 05:48 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordResetService.java
> +        }
예시) 한 유저는 리셋 코드를 10개를 미리 발급해두었다. 이후 리셋 코드를 필요할 때마다 기존 발급한 코드를 사용했다.

위 동작을 의도한 건 아니지 않나요?

2024-11-12 07:26 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordResetService.java
> +    }
코드가 확인되었는지 확인하는 변수를 추가하는 방식으로 변경했습니다!

2024-11-12 07:54 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/ConfirmPasswordResetCodeRequest.java
> +}
Code도 @NotBlank 필요하지 않나요 👀

2024-11-12 08:32 UTC, tsulocalize approved these changes
수고하셨습니다!

2024-11-13 02:12 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/ConfirmPasswordResetCodeRequest.java
> +}
code랑 newPassword도 추가해줬습니다!

2024-11-13 07:10 UTC, JINU-CHANG approved these changes
카피 수고많으셨어요 ~~ 👍

2024-11-13 07:10 UTC, shin-jisong approved these changes
수고하셨습니다!

2024-11-13 07:10 UTC, merged