[BE] 체크리스트 카테고리별 질문 비교 기능을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #963
Opened 2024-11-16 05:38 UTC by JINU-CHANG

## ❗ Issue

- #961 

## ✨ 구현한 기능

- [ ] 카테고리별 질문 조회 API

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-11-16 11:09 UTC, tsulocalize requested changes
간단한 리뷰만 남겼습니다.
추가로, 개수(숫자)나 %값은 서버 단에서 주지 않기로 이미 합의되는지 궁금하네요!

2024-11-16 11:09 UTC, tsulocalize commented on backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
> +        Assertions.assertThat(bad).hasSize(1);
static import를 쓰면 가독성이 올라갈 것 같네요!

2024-11-16 11:09 UTC, tsulocalize commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
> +                .map(checklistQuestion -> new QuestionResponse(checklistQuestion.getQuestion(), questionService.readHighlights(checklistQuestion.getQuestionId())))
Highlight가 비교 페이지에서 꼭 필요하지 않다면 가져오지 않는 방향으로 가는 게 더 좋아보이긴 합니다!

2024-11-16 15:58 UTC, tkdgur0906 requested changes
고생하셨습니다! 리뷰 남겼는데 한번 확인 부탁드려요!

궁금한게 있는데, 저희가 카테고리의 질문과 답변을 답변 기준으로 나눠서 보내면, 이 데이터를 그대로 보여주기 위한 api인가요 아니면 프론트에서 추가작업을 하는 건가요?

2024-11-16 15:58 UTC, tkdgur0906 commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/ComparisonCategoryChecklistQuestionResponse.java
> +public record ComparisonCategoryChecklistQuestionResponse(List<QuestionResponse> good,
dto이름이 한눈에 와닿지 않는 것 같은데, 가지고 있는 데이터를 이름에 담는 방향은 어떻게 생각하시나요?

`AnswerCategorizedQuestionsResponse` 이런 느낌으로 생각해봤는데 정확하게 어떤게 좋을지는 잘 모르겠네요🤔

2024-11-16 15:58 UTC, tkdgur0906 commented on backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
> +        Assertions.assertThat(none).isEmpty();
assertAll로 묶는 건 어떤가요!?

2024-11-18 04:13 UTC, shin-jisong reviewed
딱히 큰 피드백은 없네요!
수고하셨습니다~

2024-11-18 04:13 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
> +    @GetMapping("/v1/comparison/checklists/{checklistId}/categories/{categoryId}/questions")
queryString으로 설계하지 않고 계층적으로 설계하신 이유가 궁금해요!
계층적 설계가 들어가서 checklists가 먼저 나오니 QuestionController에 위치한 게 어색하다는 생각도 들어서요~

2024-11-18 11:01 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
> +    }
matchAnswer로 변경했습니다!

2024-11-18 11:03 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
> +        Assertions.assertThat(none).isEmpty();
반영했습니다!

2024-11-18 11:03 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
> +        Assertions.assertThat(bad).hasSize(1);
반영했습니다!

2024-11-20 10:24 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
> +                .map(checklistQuestion -> new QuestionResponse(checklistQuestion.getQuestion(), questionService.readHighlights(checklistQuestion.getQuestionId())))
논의 후 하이라이트 가져가는 것으로 결정했습니다.

2024-11-20 10:52 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
> +    @GetMapping("/v1/comparison/checklists/{checklistId}/categories/{categoryId}/questions")
> queryString으로 설계하지 않고 계층적으로 설계하신 이유가 궁금해요!

queryString은 리소스들을 정렬하거나 필터링할 때, pathvariable은 구체적인 리소스의 위치를 지정할 때 사용한다고 알고 있습니다.
다시 살펴보니 여러 질문들 중에서 특정 카테고리만 필터링해서 전달하고 있기 때문에 `/v1/comparison/checklists/{checklistId}/questions?category={categoryId}` 이런 설계가 더 적절해보이네요!
이 부분은 변경 가능한지 프론트와 상의해보겠습니다. 앞으로 API 설계도 백엔드에서 확정지은 후에 프론트에 공유해야겠어요 🙂

> 계층적 설계가 들어가서 checklists가 먼저 나오니 QuestionController에 위치한 게 어색하다는 생각도 들어서요

checklist 자체는 구체적으로 리소스의 위치를 전달하고 있기 때문에 pahtvariable이 적절하다고 생각했습니다. 또한 경로는 상위에서 하위로 점차 구체화되는 구조가 직관적이라고 생각해서 checklists가 먼저 나오는 것도 괜찮다고 생각했습니다.

2024-11-20 11:01 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/ComparisonCategoryChecklistQuestionResponse.java
> +public record ComparisonCategoryChecklistQuestionResponse(List<QuestionResponse> good,
좋은 것 같아요! 수정하겠습니다 👍

2024-11-21 04:58 UTC, merged