[FE] 새 방 비교 페이지를 완성하고 방 선택 페이지를 만들어 연결한다.
woowacourse-teams/2024-bang-ggood pull request #973
Opened 2024-11-19 03:03 UTC by ooherin

## ❗ Issue

- #952

## ✨ 구현한 기능

## 비교 선택 페이지를 만들었습니다. 

디자인은 다음과 같습니다.

<img width="200" alt="스크린샷 2024-11-19 오후 3 05 09" src="https://github.com/user-attachments/assets/3941ad3f-48a5-4c26-94e0-043cb512b4ba">

<img width="200" alt="스크린샷 2024-11-19 오후 3 05 23" src="https://github.com/user-attachments/assets/15ebe5cd-d6df-4522-9ddb-264e2ef415e1">

<img width="194" alt="스크린샷 2024-11-19 오후 3 22 25" src="https://github.com/user-attachments/assets/1114ae84-5d20-46da-b625-6c526e281dfa">

<img width="193" alt="스크린샷 2024-11-19 오후 3 22 46" src="https://github.com/user-attachments/assets/af14078c-b819-4359-a3b8-e7db83ea2613">

### 1. 기존의 컴포넌트들을 재사용하였으며, 몇 컴포넌트를 리팩토링 했습니다. 
`ChecklistQuestion`, `CustomBanner` 등을 재사용성 있게 리팩토링 하여 사용했습니다.

### 2. Marker 라는 새로운 컴포넌트를 만들었습니다. 
`Marker(새로 생긴 공용 컴포넌트)` 라는 새로운 공용 컴포넌트를 만들어 지하철 호선 표시마크, 비교 페이지에 A,B 표시에 사용해 주었습니다.

## 📢 논의하고 싶은 내용

디자인 관련 얘기긴 한데, 메인 페이지에서 방의 아이콘을 빨간색을 빼는 것(노란색으로 대체) 을 어떻게 생각하시는지 궁금합니다. 비교 페이지에서 빨간색이 시맨틱으로 쓰여서, 방 또한 빨간색의 경우 부정적인 의미가 생겼다고 생각합니다.  아티클의 경우는 관련이 없으니까 유지하도 될 것 같습니다. 디자인적으로도 색상이 덜 다채로워서 더 예쁘다고 생각하는데, 방의 경우는 다음과 같이 바꾸는 것에 대해 어떻게 생각하시나요? 

<img width="200" alt="스크린샷 2024-11-21 오후 7 13 45" src="https://github.com/user-attachments/assets/94ffea83-86be-48c5-8c6f-88a6c756f491">

<img width="200" alt="스크린샷 2024-11-21 오후 7 15 42" src="https://github.com/user-attachments/assets/3e2bc2af-2911-4f9f-81f2-d47a820e871a">

## 🎸 기타

2024-11-21 23:33 UTC, ooherin commented on frontend/src/components/ChecklistDetail/ChecklistAnswerSection.tsx
> +              {category.questions.map((question, index) => (
불필요한 depth 를 줄였습니다.

2024-11-21 23:33 UTC, ooherin commented on frontend/src/components/EditChecklist/ChecklistContent/EditChecklistQuestionTemplate.tsx
> +              <S.QuestionBox key={question.questionId}>
ChecklistQuestionItem을 제사용하기 위해 해당 컴포넌트의 Wrapper 를 제거하여 리팩토링하였습니다.

2024-11-22 12:07 UTC, skiende74 reviewed
수고하셨습니다

논의에대한답: 저는 색상은 어느 쪽이 되든 괜찮긴 한데, 굳이 고르라면 왼쪽(노랑)이 조금 더 좋은 것 같네요

2024-11-23 01:38 UTC, ooherin commented on frontend/src/pages/RoomCompareSelectPage.tsx
> +    <>
앗 원래는 방 3개까지 비교가 되는 로직이었지만 2개의 방을 비교하는 로직으로 바뀌었습니다. 내부적인 디자인도 많이 바뀌어서 일부분만 사용했었는데요.기존 코드에 테스트 코드랑 스토리북 코드가 들어가있는 건 몰랐네요! 이 부분은 확인 후 반영해보도록 하겠습니다. 알려주셔서 감사해요😁
제이드도 취준으로 바쁘실텐데 화이팅입니다👏

2024-11-23 15:25 UTC, healim01 requested changes
확인했습니다~! 수고 많으셨어요 리안~~!! 

방 비교 페이지가 결국 다시 멋지게 돌아왔네요 
새로 변경된 메인도 계속 빨간 아이콘이 신경쓰이신다면 변경해도 괜찮을거 같습니다~ 

다만 아직 내부에 목데이터가 있는거 같아서 비교 api 를 모두 연결된 후 완전한 코드로 올라가는게 좋지 않을까 생각이 듭니다! 

그리고 추가적으로 제안드릴 이야기는 코드 스타일 중 `index.ts` 를 사용해서 컴포넌트나 훅들을 가져오는 것에 대해서 어떻게 생각하시는지 물어보고 싶어요! 생각보다 저희 코드의 임포트 부분이 길다고 생각이 들어서요~!! 

리안과 제이드는 어떻게 생각하시나요?

2024-11-23 15:25 UTC, healim01 commented on frontend/src/components/_common/Accordion/AccordionHeader.tsx
> +  isShowMarkerIfOpen = true,
이게 추가된 이유는 마커를 안보여주고 싶을 때가 있어서 그랬을까요?

2024-11-23 15:25 UTC, healim01 commented on frontend/src/components/_common/Map/RoomCompareMap.tsx
> +                text={'B방'}
방 비교 api 가 완성되었다고 들어서 mock 으로 처리될 걸 처리하고 머지되면 좋을거 같네요!

2024-11-23 15:25 UTC, healim01 commented on frontend/src/mocks/fixtures/checklistList.ts
> +      roomName: '예시용 체크리스트',
e2e 테스트 때문에 기존 데이터를 삭제하신걸까요?

2024-11-23 15:25 UTC, healim01 commented on frontend/src/pages/RoomCompareSelectPage.tsx
> +    <>
그러게요 그때 열심히 작성한 코드,,,, 이렇게 돌아올지 알았다면 지우지 말껄,,,

2024-11-24 09:48 UTC, ooherin commented on frontend/src/components/RoomCompare/CategoryDetailModal.tsx
> +
임시 타입이었지만 실제 적용하는 타입이 되었습니다!

2024-11-24 09:50 UTC, ooherin commented on frontend/src/components/_common/Accordion/AccordionHeader.tsx
> +  isShowMarkerIfOpen = true,
![스크린샷 2024-11-24 오후 6 49 33](https://github.com/user-attachments/assets/366e2369-c333-4fd5-87b5-8d5734a46c1e)

이번 디테일 모달을 구현하면서, 열린 경우에도 '시멘틱 라벨 색상' 을 보여주고 싶어서 구현하였습니다. 
디테일 페이지의 아코디언에서는 닫힐 때는 라벨이 보이지 않는데, 이를 분기처리 해서 사용할려고 구현했어요!

2024-11-24 09:50 UTC, ooherin commented on frontend/src/components/_common/Map/RoomCompareMap.tsx
> +                text={'B방'}
네네! 완성했습니다

2024-11-24 09:51 UTC, ooherin commented on frontend/src/mocks/fixtures/checklistList.ts
> +      roomName: '예시용 체크리스트',
어떤 데이터를 삭제했다는 건지 이해를 잘 못했는데, 위 변경은 '예시용 체크리스트' 가 '비교 대상' 에서 빠지는 것을 테스트하기 위해서 변경한 것입니다~! 물어보신게 이게 아니라면 다시 알려주세용!

2024-11-24 11:20 UTC, skiende74 commented
> 코드 스타일 중 `index.ts` 를 사용해서 컴포넌트나 훅들을 가져오는 것

배럴 파일을 쓰면 트리쉐이킹이 무력화되고, 순환참조 가능성이 증가하는 점 때문에 피하고 싶어요. !

- 순환참조 등 개괄 : [Please Stop Using Barrel Files - Tkdodo ](https://tkdodo.eu/blog/please-stop-using-barrel-files)
- 트리쉐이킹 관련 : [Barrel files and why you should STOP using them now - Dev.to](https://dev.to/tassiofront/barrel-files-and-why-you-should-stop-using-them-now-bc4)
- minor:빌드성능관련 : [배럴(Barrel) 파일의 대실패 - Korean FE Article](https://kofearticle.substack.com/p/korean-fe-article-barrel)

2024-11-24 20:53 UTC, skiende74 commented
> * 이러한 논의가 생기면 관련없는 PR 보다는 이제 issue 에 올려서 논의하는 건 어떤지 건의해봅니다! 😀

좋은 것 같습니다 !

덤으로 Github을 적극적으로 활용하는 곳에서는 discussion을 파서 논의하는 방법을 쓰던데 이 방법은 어떻게 생각하시는지 궁금합니다. (#990)
( 이슈든 디스커션이든 좋습니다. )

2024-11-27 18:32 UTC, skiende74 approved these changes
시간이 좀 걸리신다면 우선 머지하고 추후PR에서 반영하셔도 좋을거같습니다 !!

2024-11-29 04:03 UTC, merged