[BE] 체크리스트 방 비교 기능을 구현한다.
woowacourse-teams/2024-bang-ggood pull request #979
Opened 2024-11-20 07:30 UTC by shin-jisong

## ❗ Issue

- #974 

## ✨ 구현한 기능
체크리스트 방 비교 기능 구현

## 📢 논의하고 싶은 내용

## 🎸 기타

2024-11-20 11:34 UTC, JINU-CHANG requested changes
시소 코드양만 보아도 고생이 정말 많으셨을 것 같아요 🥹 수고하셨습니다~~~~

2024-11-20 11:34 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
> +    @GetMapping("/v1/checklists/compare")
REST API에서는 자원 중심으로 설계하기 때문에 행위는 HTTP 메서드로 나타내고 URI는 명사구를 사용한다고 알고 있습니다. 다른 방식으로 표현해볼 수 없을까요? 🤔

2024-11-20 11:34 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
> +                checklistId, categoryId, Answer.GOOD);
AnsweredQuestions을 먼저 가져오고 Answer.GOOD인 것만 필터링해서 갯수를 확인하면 2번 데이터베이스에 요청을 보내지 않아도 될 것 같아요!

2024-11-20 11:34 UTC, JINU-CHANG commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
> +    }
비교를 위한 계산 로직이 꽤 중요한 도메인이라고 생각하는데 도메인 내부에서 처리하는 건 어떤가요? 🤔

2024-11-20 11:34 UTC, JINU-CHANG commented on backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
> +    }
계산 로직을 가진 도메인이 있다면 해당 테스트도 도메인 테스트로 변경할 수 있을 것 같아요~

2024-11-24 07:48 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
> +                checklistId, categoryId, Answer.GOOD);
리팩토링 PR로 반영하겠습니다!!

2024-11-24 07:48 UTC, shin-jisong commented on backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
> +    }
리팩토링 PR로 반영하겠습니다!!

2024-11-24 07:48 UTC, shin-jisong commented on backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
> +    }
리팩토링 PR로 반영하겠습니다!!

2024-11-24 07:58 UTC, merged